Repository stolostron/rhacm-docs, pull requests merged in 2021-06, with the labels that each got.

#2171 2.0 stage refresh for Errata
  install/requirements.adoc
  release_notes/fixpack.adoc
  release_notes/known_issues.adoc
Labels: lgtm

#2162 open-cluster-management/backlog#10276 copy ts local cluster
  troubleshooting/master.adoc
  troubleshooting/trouble_local_cluster.adoc
  troubleshooting/troubleshooting_intro.adoc
Labels: lgtm

#2139 Adding what's new entry for retentionConfig in mco
  apis/observability.json.adoc
  observability/observability_enable.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#2177 updating the link to the memory usage policy
  risk_compliance/memory_policy.adoc
Labels: lgtm

#2187 Refresh 06/04/21
  install/install_connected.adoc
  install/requirements.adoc
  manage_cluster/create_bare.adoc
  security/memory_policy.adoc
  troubleshooting/must_gather.adoc
Labels: lgtm

#2192 Swope cred 4
  access_control/access_intro.adoc
  access_control/credential_auth_intro.adoc
  access_control/main.adoc
  credentials/credential_aws.adoc
  credentials/credential_azure.adoc
  credentials/credential_bare.adoc
  credentials/credential_google.adoc
  credentials/credential_intro.adoc
  credentials/credential_openstack.adoc
  credentials/credential_vm.adoc
  credentials/main.adoc
  credentials/master.adoc
  credentials/modules
  troubleshooting/trouble_agent_credentials.adoc
Labels: needs-rebase

#2193 Fix design_grafana typo
  observability/design_grafana.adoc
Labels: lgtm

#2206 update invalid object storage secret example.
  observability/observability_enable.adoc
Labels: lgtm

#2207 update invalid object storage secret example
  observing_environments/observability_enable.adoc
Labels: lgtm

#2176 Update observability.json.adoc
  apis/observability.json.adoc
Labels: lgtm

#2108 updates for MGMT-297
  clusters/bare_assets.adoc
  clusters/create_bare.adoc
Labels: lgtm

#2230 open-cluster-management/backlog#12954 Upd vmw req
  install/plan_capacity.adoc
Labels: lgtm

#2234 open-cluster-management/backlog#12620 deprecation from 2.2.
  release_notes/deprecate_remove.adoc
Labels: lgtm

#2236 open-cluster-management/backlog#11208 -- adding deprecations
  release_notes/deprecate_remove.adoc
Labels: lgtm

#2227 open-cluster-management/backlog#11454 ch import cmd
  manage_cluster/import_gui.adoc
Labels: lgtm

#2241 2.2.4 refresh 06/16/21
  install/install_disconnected.adoc
  install/plan_capacity.adoc
  manage_cluster/create_bare.adoc
  manage_cluster/import_gui.adoc
  observing_environments/observability_enable.adoc
  observing_environments/observe_environments.adoc
  release_notes/deprecate_remove.adoc
  release_notes/errata.adoc
  security/cert_policy_ctrl.adoc
Labels: lgtm

#2239 Update certificates.adoc
  risk_compliance/certificates.adoc
Labels: lgtm

#2242 Update errata.adoc
  release_notes/errata.adoc
Labels: lgtm

#2248 Refresh update for 2.2.4 06/16/21
  observing_environments/observability_enable.adoc
  release_notes/errata.adoc
Labels: lgtm

#2149 adding api for multiclusterhub
  apis/main.adoc
  apis/multicluster_hub.json.adoc
  apis/policy.json.adoc
Labels: lgtm

#2240 Updating gatekeeper doc
  risk_compliance/gatekeeper_policy.adoc
Labels: lgtm

#2262 Search file not displayed in Safari 2.2
  release_notes/known_issues.adoc
Labels: lgtm

#2251 updating the RBAC docs
  access_control/rbac.adoc
Labels: do-not-merge/hold

#2283 Update Discovery docs
  clusters/discovery_config_cli.adoc
  clusters/discovery_config_ui.adoc
  clusters/discovery_credential.adoc
Labels: lgtm

#2284 fix typo
  observability/customize_observability.adoc
Labels: lgtm

#2295 open-cluster-management/backlog#13239 Swope errata1.8
  release_notes/errata.adoc
Labels: lgtm

#2297 2.1.8 Refresh
  install/requirements.adoc
  release_notes/errata.adoc
  troubleshooting/master.adoc
  troubleshooting/trouble_local_cluster.adoc
  troubleshooting/troubleshooting_intro.adoc
Labels: lgtm, needs-rebase

#2271 validate the doc for dashboard design
  observability/design_grafana.adoc
Labels: lgtm

#2302 Refresh 06/24/21
  apis/api.adoc
  apis/master.adoc
  apis/multicluster_hub.json.adoc
  manage_cluster/intro.adoc
  manage_cluster/master.adoc
  manage_cluster/scale.adoc
  observing_environments/design_grafana.adoc
  observing_environments/observe_environments.adoc
  release_notes/known_issues.adoc
  security/gatekeeper_policy.adoc
Labels: lgtm

#2299 updating the list of supported object stores for obs
  observability/observe_environments.adoc
Labels: lgtm

#2306 fix errors in enable observability doc.
  observability/observability_enable.adoc
Labels: lgtm

#2301 open-cluster-management/backlog#13682 DDF fix repo
  security/create_policy_ctrl.adoc
Labels: lgtm

#2303 add alert forward feature in doc.
  observability/observability_enable.adoc
Labels: lgtm

#2316 set the type for resources in observabilityAddonSpec
  apis/observability.json.adoc
Labels: lgtm

#2318 update resource request doc
  observing_environments/observe_environments.adoc
Labels: lgtm

#2304 update resource request doc
  observability/observe_environments.adoc
Labels: lgtm

#2274 add api doc for placement/placementdecision
  apis/api.adoc
  apis/main.adoc
  apis/placement.json.adoc
  apis/placementdecision.json.adoc
Labels: lgtm

#2323 Mj redisgraph 13679
  release_notes/known_issues.adoc
Labels: lgtm

#2322 2.2 refresh
  observing_environments/customize_observability.adoc
  observing_environments/observe_environments.adoc
  release_notes/errata.adoc
  release_notes/known_issues.adoc
  security/create_policy_ctrl.adoc
Labels: lgtm
