Repository stolostron/rhacm-docs, pull requests merged in 2021-09, with the labels that each got.

#2624 open-cluster-management/backlog#12010 Rev
  clusters/proxy.adoc
Labels: lgtm

#2644 Updating OCS to RH OpenShift Data Foundation
  observability/observability_enable.adoc
Labels: lgtm

#2579 open-cluster-management/backlog#11111 rem note cred upd
  credentials/credential_ansible.adoc
Labels: lgtm

#2654 Refresh for 2.3.2 09/07/21
  applications/manage_apps_git.adoc
  clusters/proxy.adoc
  credentials/credential_ansible.adoc
  install/install_overview.adoc
  observability/observability_enable.adoc
  observability/observe_environments.adoc
  release_notes/errata.adoc
  release_notes/known_issues.adoc
Labels: lgtm

#2650 open-cluster-management/backlog#15193 Select job
  clusters/ansible_config_cluster.adoc
Labels: lgtm

#2656 Swope install ddf (Core OS?)
  install/requirements.adoc
Labels: lgtm

#2665 Swope links5
  install/install_connected.adoc
Labels: needs-rebase

#2669 Swope api
  apis/discoveryconfig.json.adoc
Labels: needs-rebase

#2670 Swope api
  apis/api.adoc
  apis/discoveryconfig.json.adoc
Labels: needs-rebase

#2671 Refresh for 2.2.8 09/14/21
  manage_cluster/create_bare.adoc
  manage_cluster/prov_conn_bare.adoc
  observing_environments/observability_enable.adoc
  observing_environments/observe_environments.adoc
  release_notes/errata.adoc
  release_notes/known_issues.adoc
Labels: lgtm

#2672 Swope api4
  apis/discoveredcluster.json.adoc
  apis/discoveryconfig.json.adoc
Labels: needs-rebase

#2673 Swope api4
  apis/api.adoc
  apis/discoveredcluster.json.adoc
Labels: needs-rebase

#2653 no issue - artwork process additions
  _pages/images_guide.md
Labels: lgtm

#2690 Swope build8
  apis/discoveredcluster.json.adoc
  apis/discoveryconfig.json.adoc
Labels: needs-rebase

#2692 2.3 stage to prod refresh
  apis/api.adoc
  apis/discoveredcluster.json.adoc
  apis/discoveryconfig.json.adoc
  apis/main.adoc
  credentials/credential_ansible.adoc
  install/install_connected.adoc
  install/install_overview.adoc
  install/requirements.adoc
  release_notes/deprecate_remove.adoc
Labels: lgtm

#2668 Updated what's new doc with observability slo dashboard
  observability/customize_observability.adoc
  release_notes/whats_new.adoc
Labels: do-not-merge/hold

#2684 open-cluster-management/backlog#15830 disableUpdClust 24
  clusters/rel_img_conn.adoc
  clusters/sync_rel_img.adoc
  install/install_connected.adoc
Labels: lgtm

#2700 Adding support verbiage for observability
  observability/observe_environments.adoc
Labels: lgtm

#2696 open-cluster-management/backlog#16246 add 2.1.11 errata
  release_notes/errata.adoc
Labels: lgtm

#2707 Refresh for errata 2.1.11 09/22/21
  release_notes/errata.adoc
  release_notes/known_issues.adoc
  release_notes/release_notes.adoc
Labels: lgtm

#2711 open-cluster-management/backlog#15997
  install/install_connected.adoc
Labels: lgtm

#2723 RBAC known issue automation policies [2.3]
  release_notes/known_issues.adoc
Labels: lgtm

#2725 open-cluster-management/backlog#15794 ki ans fail
  release_notes/known_issues.adoc
Labels: lgtm

#2727 open-cluster-management/backlog#16250
  release_notes/known_issues.adoc
Labels: lgtm

#2697 open-cluster-management/backlog#13792 namespace
  install/requirements.adoc
Labels: lgtm

#2693 Update AWS gateway instance type to c5d.large
  services/deploy_submariner.adoc
  services/deploy_submariner_api.adoc
Labels: lgtm
