Repository stolostron/rhacm-docs, pull requests merged in 2021-12, with the labels that each got.

#2984 open-cluster-management/backlog#18197--change to version
  clusters/backup_and_restore.adoc
Labels: lgtm

#2996 Refresh 12-2
  about/quick_start.adoc
  applications/app_advanced_config.adoc
  applications/app_management_overview.adoc
  applications/app_model.adoc
  applications/gitops_config.adoc
  applications/managing_secrets.adoc
  applications/secret_sample.adoc
  clusters/backup_and_restore.adoc
  clusters/backup_restore_enable.adoc
  clusters/cluster_pool_manage.adoc
  clusters/create_bare.adoc
  clusters/remove_managed_cluster.adoc
  clusters/supported_clouds.adoc
  governance/policy_controllers.adoc
  install/adv_config_install.adoc
  install/install_connected.adoc
  install/install_disconnected.adoc
  install/install_overview.adoc
  install/main.adoc
  install/perform_scale.adoc
  install/plan_capacity.adoc
  modules/common-attributes.adoc
  observability/customize_observability.adoc
  observability/manage_insights.adoc
  observability/observe_environments.adoc
  release_notes/deprecate_remove.adoc
  release_notes/known_issues.adoc
Labels: lgtm

#2974 bz2027595 update API version
  clusters/imp_clust_custom_image_override.adoc
  clusters/managedclustersets.adoc
Labels: lgtm

#2999 open-cluster-management/backlog#18276 Add errata 2.1.13
  release_notes/errata.adoc
Labels: lgtm

#3000 open-cluster-management/backlog#18277 add errata 2.2.10
  release_notes/errata.adoc
Labels: lgtm

#2998 open-cluster-management/backlog#16626-install stuck in status
  troubleshooting/main.adoc
  troubleshooting/trouble_install_status.adoc
  troubleshooting/troubleshooting_intro.adoc
Labels: lgtm

#3008 Refresh for 2.1.13 12/06/21
  release_notes/errata.adoc
Labels: lgtm

#3007 Refresh for 2.2.10 12/06/21
  release_notes/errata.adoc
  release_notes/known_issues.adoc
  security/etcd_encryption_policy.adoc
Labels: lgtm

#3006 Refresh for 2.3.5 12/06/21
  release_notes/errata.adoc
  release_notes/known_issues.adoc
Labels: lgtm

#3004 open-cluster-management/backlog#18012 rem ki 2.4.1 only - no ocp version
  release_notes/known_issues.adoc
Labels: lgtm

#3002 open-cluster-management/backlog#18258 add errata 2.4.1
  release_notes/errata.adoc
Labels: lgtm

#3012 Refresh for 2.4.1 12/07/21
  clusters/create_infra_env.adoc
  clusters/imp_clust_custom_image_override.adoc
  clusters/managedclustersets.adoc
  release_notes/errata.adoc
  release_notes/known_issues.adoc
  troubleshooting/main.adoc
  troubleshooting/trouble_install_status.adoc
  troubleshooting/troubleshooting_intro.adoc
Labels: lgtm

#3016 Refresh for 2.2.10 GA 12/09/21
  release_notes/errata.adoc
Labels: lgtm

#3021 Updating the description for observability
  install/perform_scale.adoc
Labels: lgtm, approved

#3022 Swope note detach
  clusters/remove_managed_cluster.adoc
Labels: needs-rebase

#3027 Edits (discovered while working) https://github.com/open-cluster-mana…
  clusters/remove_managed_cluster.adoc
Labels: lgtm

#3029 Refresh 12/16/21 2.3
  clusters/remove_managed_cluster.adoc
  install/requirements.adoc
  release_notes/known_issues.adoc
  troubleshooting/main.adoc
  troubleshooting/trouble_install_status.adoc
  troubleshooting/troubleshooting_intro.adoc
Labels: lgtm

#3028 Refresh 12/16/21 2.4
  clusters/create_infra_env.adoc
  clusters/import_cli.adoc
  clusters/remove_managed_cluster.adoc
  images/observability-arch-24.png
  install/install_connected.adoc
  install/perform_scale.adoc
  install/requirements.adoc
  observability/observe_environments.adoc
  release_notes/known_issues.adoc
  services/submariner.adoc
Labels: lgtm

#3019 Swope known issues 2.3
  release_notes/known_issues.adoc
Labels: lgtm

#3030 open-cluster-management/backlog#17790--known issue about detach
  release_notes/known_issues.adoc
Labels: lgtm

#3010 Discourage manually self-managing hub
  install/adv_config_install.adoc
Labels: lgtm
