Repository stolostron/rhacm-docs, pull requests merged in 2022-06, with the labels that each got.

#3402 stolostron/backlog#21395 submar openstack
  add-ons/submariner/submariner_prepare_hosts.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#3487 Document the evaluationInterval never value
  governance/config_policy_ctrl.adoc
Labels: lgtm

#3482 stolostron/backlog#21497 rel img visible 2.4
  clusters/release_images.adoc
Labels: lgtm

#3481 stolostron/backlog#21497 rel img visible 2.5
  clusters/release_images.adoc
Labels: lgtm

#3500 all over the place with TP
  about/master.html
  clusters/cluster_pool_manage.adoc
  clusters/create_bare.adoc
  clusters/master.html
  console/master.html
  governance/certificates.adoc
  governance/integrity_shield.adoc
  governance/security_intro.adoc
  install/adv_config_install.adoc
  install/upgrade_hub.adoc
  multicluster_engine/addon_managed_service.adoc
  multicluster_engine/adv_config_install.adoc
  release_notes/fips_readiness.adoc
  release_notes/master.html
  release_notes/whats_new.adoc
Labels: lgtm

#3522 stolostron/backlog#22559 ki sushy-tools
  release_notes/known_issues.adoc
Labels: lgtm

#3538 Clarify hub template docs
  governance/custom_template.adoc
Labels: lgtm

#3539 [2.4_stage] Clarify hub template docs
  governance/custom_template.adoc
Labels: lgtm

#3524 stolostron/backlog#20335--new topic
  applications/allow_deny.adoc
  applications/app_management_overview.adoc
  applications/main.adoc
  applications/subscription_report.adoc
Labels: lgtm

#3521 stolostron/backlog#22112 deprecate bma
  clusters/bare_assets.adoc
  clusters/create_bare.adoc
  release_notes/deprecate_remove.adoc
Labels: lgtm

#3503 Updating certs doc
  governance/certificates.adoc
Labels: lgtm

#3480 stolostron/backlog#21626--enable klusterlet addon
  add-ons/addon_overview.adoc
  add-ons/klusterlet_managed.adoc
  add-ons/main.adoc
  add-ons/submariner/submariner.adoc
  add-ons/submariner/submariner_serv_disc.adoc
  add-ons/volsync/volsync_convert_backup.adoc
  add-ons/volsync/volsync_replicate.adoc
  add-ons/volsync/volsync_schedule.adoc
Labels: lgtm

#3576 Refresh 6/9/22 morning
  add-ons/addon_overview.adoc
  add-ons/klusterlet_managed.adoc
  add-ons/main.adoc
  add-ons/submariner/submariner.adoc
  add-ons/submariner/submariner_prepare_hosts.adoc
  add-ons/submariner/submariner_serv_disc.adoc
  add-ons/submariner/submariner_uninstall.adoc
  add-ons/volsync/volsync_convert_backup.adoc
  add-ons/volsync/volsync_replicate.adoc
  add-ons/volsync/volsync_schedule.adoc
  apis/observability.json.adoc
  applications/gitops_config.adoc
  clusters/intro.adoc
  clusters/managedclustersets_assign_role.adoc
  clusters/single_node_openshift.adoc
  governance/policy_generator.adoc
  install/cluster_size.adoc
  install/install_connected.adoc
  install/uninstall.adoc
  observability/customize_observability.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#3542 stolostron/backlog#22261 ki subm mtu
  release_notes/known_issues.adoc
Labels: lgtm

#3588 Refresh link issues 06/10/22
  add-ons/submariner/submariner_deploy_mcaddon_api.adoc
  add-ons/submariner/submariner_uninstall.adoc
  add-ons/volsync/volsync_replicate.adoc
  install/install_disconnected.adoc
  install/upgrade_hub.adoc
  release_notes/known_issues.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#3589 Update subctl URL from tech preview to v0.12
  add-ons/submariner/submariner.adoc
Labels: lgtm

#3551 Updating the Backup and restore doc
  clusters/backup_and_restore.adoc
  clusters/backup_restore_enable.adoc
Labels: lgtm

#3601 Remove outdated Submariner prerequisites
  add-ons/submariner/submariner.adoc
Labels: lgtm, unplanned

#3605 Swope matrix2.4
  install/requirements.adoc
Labels: needs-rebase

#3603 stolostron/backlog#22064
  install/upgrade_hub.adoc
Labels: lgtm

#3614 update disconnected install
  install/install_disconnected.adoc
Labels: lgtm, unplanned

#3615 refresh 6/16
  add-ons/klusterlet_managed.adoc
  add-ons/submariner/submariner.adoc
  clusters/backup_and_restore.adoc
  clusters/backup_restore_enable.adoc
  clusters/create_cluster_on_prem.adoc
  clusters/create_infra_env.adoc
  clusters/create_ocp_aws.adoc
  clusters/rel_img_conn.adoc
  clusters/single_node_openshift.adoc
  console/console.adoc
  install/install_disconnected.adoc
  install/requirements.adoc
  install/upgrade_hub.adoc
  multicluster_engine/main.adoc
  observability/customize_observability.adoc
  release_notes/known_issues.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#3620 [2.5_stage] Update integrity_shield.adoc
  governance/integrity_shield.adoc
Labels: lgtm

#3623 Swope install add
  install/upgrade_hub.adoc
Labels: needs-rebase

#3624 2.4 stage refresh and errata
  clusters/create_infra_env.adoc
  clusters/placement_managed.adoc
  clusters/release_images.adoc
  console/console.adoc
  governance/custom_template.adoc
  governance/image_vuln_policy.adoc
  governance/integrity_shield.adoc
  governance/memory_policy.adoc
  governance/namespace_policy.adoc
  governance/pod_policy.adoc
  governance/policy_controllers.adoc
  governance/psp_policy.adoc
  governance/role_policy.adoc
  governance/rolebinding_policy.adoc
  install/requirements.adoc
  install/upgrade_hub.adoc
  observability/observe_environments.adoc
  release_notes/errata.adoc
Labels: lgtm

#3593 Adding upgrade step for backup and restore
  clusters/backup_restore_enable.adoc
  release_notes/known_issues.adoc
Labels: lgtm

#3628 Refresh 2.5 June 23
  add-ons/submariner/submariner.adoc
  add-ons/submariner/submariner_deploy_mcaddon_api.adoc
  clusters/backup_restore_enable.adoc
  clusters/remove_managed_cluster.adoc
  governance/integrity_shield.adoc
  multicluster_engine/install_disconnected.adoc
  release_notes/known_issues.adoc
  troubleshooting/must_gather.adoc
Labels: lgtm

#3632 stolostron/backlog#23645 add 2.3.11 docs errata
  release_notes/errata.adoc
Labels: lgtm

#3635 Refresh 6/28
  about/supported_providers.adoc
  install/cluster_size.adoc
  install/requirements.adoc
  observability/customize_observability.adoc
Labels: lgtm

#3637 refresh 6/28
  clusters/backup_and_restore.adoc
  release_notes/errata.adoc
  release_notes/release_notes.adoc
Labels: lgtm

#3645 Remove duplicate
  clusters/upgrade_cluster_discon.adoc
Labels: lgtm

#3647 Fixing typo using VSC w/Oliver
  governance/pod_policy.adoc
Labels: lgtm

#3634 stolostron/backlog#23648--numerous known issues and task entry for ba…
  clusters/create_bare.adoc
  clusters/create_vm.adoc
  release_notes/known_issues.adoc
Labels: lgtm
