Repository stolostron/rhacm-docs, pull requests merged in 2022-08, with the labels that each got.

#3765 Swope version wrong
  access_control/access_intro.adoc
  access_control/rbac.adoc
  applications/gitops_config.adoc
  applications/subscription_admin.adoc
  clusters/cluster_lifecycle_architecture.adoc
  clusters/cluster_pool_manage.adoc
  clusters/create_azure.adoc
  clusters/create_bare.adoc
  clusters/create_cluster_on_prem.adoc
  clusters/create_google.adoc
  clusters/create_infra_env.adoc
  clusters/create_ocp_aws.adoc
  clusters/create_openstack.adoc
  clusters/create_vm.adoc
  clusters/import_cli.adoc
  clusters/import_gui.adoc
  clusters/single_node_openshift_cluster_pool_create.adoc
  clusters/upgrade_cluster_discon.adoc
  credentials/credential_aws.adoc
  credentials/credential_azure.adoc
  credentials/credential_bare.adoc
  credentials/credential_google.adoc
  credentials/credential_on_prem.adoc
  governance/certificates.adoc
  governance/compliance_operator_policy.adoc
  governance/create_gatekeeper.adoc
  governance/create_policy_ctrl.adoc
  governance/custom_template.adoc
  governance/deploy_gitops.adoc
  governance/e8_scan_policy.adoc
  governance/etcd_encryption_policy.adoc
  governance/ocp_cis_policy.adoc
  governance/policy_generator.adoc
  governance/scc_policy.adoc
  governance/secure_rhacm.adoc
  install/install_connected.adoc
  install/perform_scale.adoc
  install/uninstall.adoc
  install/upgrade_hub.adoc
  multicluster_engine/install_connected.adoc
  multicluster_engine/install_disconnected.adoc
  observability/insights_observability.adoc
  observability/observability_enable.adoc
  observability/observe_environments.adoc
  release_notes/fips_readiness.adoc
  release_notes/known_issues.adoc
  troubleshooting/must_gather.adoc
  troubleshooting/trouble_reinstall.adoc
  troubleshooting/trouble_vm_cluster.adoc
Labels: lgtm

#3777 Fix the OpenShift GitOps init command
  governance/policy_generator.adoc
Labels: lgtm

#3779 Instruct the user to set the version when installing the PG
  governance/policy_generator.adoc
Labels: lgtm

#3785 2.3 refresh (cluster doc deprecation notice missed--updated throughout versions)
  release_notes/deprecate_remove.adoc
Labels: lgtm

#3783 2.5 stage Refresh
  access_control/access_intro.adoc
  access_control/rbac.adoc
  applications/gitops_config.adoc
  applications/subscription_admin.adoc
  clusters/backup_and_restore.adoc
  clusters/cluster_lifecycle_architecture.adoc
  clusters/cluster_pool_manage.adoc
  clusters/create_azure.adoc
  clusters/create_bare.adoc
  clusters/create_cluster_on_prem.adoc
  clusters/create_google.adoc
  clusters/create_infra_env.adoc
  clusters/create_ocp_aws.adoc
  clusters/create_openstack.adoc
  clusters/create_vm.adoc
  clusters/import_cli.adoc
  clusters/import_gui.adoc
  clusters/single_node_openshift.adoc
  clusters/single_node_openshift_cluster_pool_create.adoc
  clusters/upgrade_cluster_discon.adoc
  credentials/credential_aws.adoc
  credentials/credential_azure.adoc
  credentials/credential_bare.adoc
  credentials/credential_google.adoc
  credentials/credential_on_prem.adoc
  governance/certificates.adoc
  governance/compliance_operator_policy.adoc
  governance/create_gatekeeper.adoc
  governance/create_policy_ctrl.adoc
  governance/custom_template.adoc
  governance/deploy_gitops.adoc
  governance/e8_scan_policy.adoc
  governance/etcd_encryption_policy.adoc
  governance/ocp_cis_policy.adoc
  governance/policy_generator.adoc
  governance/scc_policy.adoc
  governance/secure_rhacm.adoc
  install/install_connected.adoc
  install/perform_scale.adoc
  install/uninstall.adoc
  install/upgrade_hub.adoc
  multicluster_engine/install_connected.adoc
  multicluster_engine/install_disconnected.adoc
  observability/insights_observability.adoc
  observability/observability_enable.adoc
  observability/observe_environments.adoc
  release_notes/deprecate_remove.adoc
  release_notes/fips_readiness.adoc
  release_notes/known_issues.adoc
  troubleshooting/must_gather.adoc
  troubleshooting/trouble_reinstall.adoc
  troubleshooting/trouble_vm_cluster.adoc
Labels: lgtm

#3782 stolostron/backlog#20569 hub cluster network
  networking/network_config_hub.adoc
  networking/network_config_managed.adoc
Labels: lgtm

#3791 https://github.com/stolostron/backlog/issues/24307
  _pages/wr_validationtools.md
Labels: lgtm

#3792 https://github.com/stolostron/backlog/issues/24307 we don't do videos…
  _pages/videos_repositories.md
Labels: lgtm

#3787 Adding the configurationPolicyAnnotations parameter
  governance/policy_generator.adoc
Labels: lgtm

#3751 stolostron/backlog#24234 updates
  clusters/disable_hosted_control_planes.adoc
  clusters/hosted_control_planes_configure.adoc
  clusters/hosted_control_planes_intro.adoc
  clusters/hypershift_cluster_destroy.adoc
  clusters/main.adoc
Labels: lgtm

#3799 Adding the whats new entry for policy generator parameter
  release_notes/whats_new.adoc
Labels: lgtm

#3810 Document concurrency for config policy controller
  governance/config_policy_ctrl.adoc
Labels: lgtm

#3819 Refresh for 8/5/22
  clusters/create_cluster_on_prem.adoc
  clusters/disable_hosted_control_planes.adoc
  clusters/hosted_control_planes_configure.adoc
  clusters/hosted_control_planes_intro.adoc
  clusters/hypershift_cluster_destroy.adoc
  clusters/main.adoc
  clusters/single_node_openshift.adoc
  clusters/upgrade_cluster_discon.adoc
  governance/deploy_gitops.adoc
  governance/policy_set_ctrl.adoc
  observability/observability_enable.adoc
  release_notes/known_issues.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#3827 Updating deprecation table for consistency
  release_notes/deprecate_remove.adoc
Labels: lgtm

#3828 Pillar name consistency for 2.4
  release_notes/deprecate_remove.adoc
Labels: lgtm

#3824 Removing Custom policy controller doc
  governance/create_policy_ctrl.adoc
  governance/main.adoc
  governance/policy_controllers.adoc
  release_notes/deprecate_remove.adoc
Labels: lgtm

#3835 Remove known issue in 2.5
  release_notes/known_issues.adoc
Labels: lgtm

#3831 update known issues of cluster lifecycle
  release_notes/known_issues.adoc
Labels: lgtm

#3823 Updating the Grafana URL
  observability/design_grafana.adoc
Labels: lgtm

#3853 Updating cluster backup and restore
  backup_restore/backup_and_restore.adoc
Labels: lgtm

#3826 update know issues for app lifecycle in ACM 2.6 release
  release_notes/known_issues.adoc
Labels: lgtm

#3871 Specify proxy config as part of outbound config in 2.3
  clusters/proxy.adoc
  observability/customize_observability.adoc
Labels: lgtm

#3876 Specify proxy config as part of outbound config in 2.4
  clusters/proxy.adoc
  observability/customize_observability.adoc
Labels: lgtm

#3884 Update import controller command in 2.5
  troubleshooting/trouble_cluster_import_fails.adoc
Labels: lgtm

#3881 update messaging for browser compatibility around dark theme
  release_notes/known_issues.adoc
Labels: lgtm

#3858 Add new troubleshooting for cluster import in 2.3
  troubleshooting/main.adoc
  troubleshooting/trouble_already_exists.adoc
Labels: lgtm

#3891 Add HyperShift cluster bug in 2.5
  release_notes/known_issues.adoc
Labels: lgtm

#3909 Refresh 2.5 8/19/22
  applications/app_model.adoc
  clusters/backup_and_restore.adoc
  clusters/proxy.adoc
  observability/customize_observability.adoc
  observability/observe_environments.adoc
  release_notes/deprecate_remove.adoc
  release_notes/known_issues.adoc
  troubleshooting/main.adoc
  troubleshooting/trouble_already_exists.adoc
  troubleshooting/trouble_cluster_import_fails.adoc
Labels: lgtm

#3929 Updating file name and links
  about/architecture.adoc
  access_control/rbac.adoc
  governance/cert_mgmt_ingress.adoc
  governance/certificates.adoc
  governance/main.adoc
  governance/security_overview.adoc
  troubleshooting/troubleshooting_intro.adoc
Labels: lgtm

#3908 Add whats new in 2.6
  release_notes/whats_new.adoc
Labels: lgtm

#3907 Replace aarch64 with arm64 in 2.5
  clusters/create_azure.adoc
  clusters/create_google.adoc
  clusters/create_ocp_aws.adoc
  clusters/create_openstack.adoc
  clusters/create_virtualization.adoc
  clusters/create_vm.adoc
Labels: lgtm

#3941 Dawson24960226
  multicluster_engine/cluster_lifecycle/placement_managed.adoc
  multicluster_engine/install_upgrade/uninstall.adoc
Labels: needs-rebase

#3936 stolostron/backlog#24626 redo host inventory
  multicluster_engine/cluster_lifecycle/add_hosts_infra_env.adoc
  multicluster_engine/cluster_lifecycle/create_cluster_on_prem.adoc
  multicluster_engine/cluster_lifecycle/create_infra_env.adoc
  multicluster_engine/credentials/credential_on_prem.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#3814 stolostron/backlog#24526 rem clc apis
  release_notes/deprecate_remove.adoc
Labels: lgtm

#3946 Quick update based on other updates in another version
  governance/policy_set_ctrl.adoc
Labels: lgtm

#3944 stolostron/backlog#25012 rem fsURL
  multicluster_engine/cluster_lifecycle/create_infra_env.adoc
Labels: lgtm

#3931 Adding everyTime mode
  governance/ansible_grc.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#3902 Update uninstall script in 2.6
  install/uninstall.adoc
Labels: lgtm

#3949 Link .0 ext ca certs in 2.6
  multicluster_engine/credentials/credential_vm.adoc
Labels: lgtm

#3962 2.5 stage
  clusters/backup_and_restore.adoc
  clusters/backup_restore_enable.adoc
  clusters/create_azure.adoc
  clusters/create_google.adoc
  clusters/create_ocp_aws.adoc
  clusters/create_openstack.adoc
  clusters/create_virtualization.adoc
  clusters/create_vm.adoc
  credentials/credential_vm.adoc
  governance/policy_set_ctrl.adoc
Labels: lgtm

#3965 Add submariner known issue in 2.6
  release_notes/known_issues.adoc
Labels: lgtm

#3950 Doc steps for discon inst img in 2.5
  clusters/create_openstack.adoc
  clusters/create_vm.adoc
Labels: lgtm

#3954 Add Ansible credentials known issue in 2.6
  release_notes/known_issues.adoc
Labels: lgtm

#3772 Fix azure cloud prepare steps
  add-ons/submariner/submariner_prepare_hosts.adoc
Labels: lgtm

#3957 2.6 mce hypershift 0825
  multicluster_engine/hosted_control_planes/hosted_control_planes_configure.adoc
Labels: lgtm

#3976 Day2 SNO cluster worker nodes
  multicluster_engine/cluster_lifecycle/create_cluster_on_prem.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#3947 stolostron/backlog#24246 add note OVN req 4.11
  add-ons/submariner/submariner.adoc
Labels: lgtm

#3842 Rj hyper 0809 2.6
  multicluster_engine/hosted_control_planes/hosted_control_planes_configure.adoc
Labels: lgtm

#3980 remove objectstore support in allow deny list feature
  applications/allow_deny.adoc
Labels: lgtm, unplanned

#3979 remove objectstore support in allow deny list feature
  applications/allow_deny.adoc
Labels: lgtm, unplanned

#3988 Add known app issue in 2.5
  release_notes/known_issues.adoc
Labels: lgtm

#3960 no issue, update based on scrum chat
  _pages/board_maintenance.md
Labels: lgtm

#3995 Add automation template options in 2.6
  multicluster_engine/cluster_lifecycle/ansible_config_cluster.adoc
Labels: lgtm

#3997 Refresh for 2.3.12 08/31/22
  clusters/proxy.adoc
  observability/customize_observability.adoc
  release_notes/deprecate_remove.adoc
  release_notes/errata.adoc
  troubleshooting/main.adoc
  troubleshooting/trouble_already_exists.adoc
Labels: lgtm

#3994 Adding matchLabels and matchExpressions to whats new
  about/quick_start.adoc
  governance/create_policy.adoc
  governance/grc_intro.adoc
  governance/main.adoc
  governance/policy_intro.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#4000 What's new final addition
  release_notes/whats_new.adoc
Labels: lgtm
