Repository stolostron/rhacm-docs, pull requests merged in 2022-09, with the labels that each got.

#4004 Add new ocp 4.11 issue in 2.6
  release_notes/known_issues.adoc
Labels: lgtm

#4010 Gov known issue policy automation
  governance/ansible_grc.adoc
Labels: lgtm

#4019 Adding link to Supported policies list
  governance/policy_sample_intro.adoc
Labels: lgtm

#4015 Remove Zettaset page
  governance/main.adoc
  governance/policy_sample_intro.adoc
  governance/zettaset_policy.adoc
  release_notes/whats_new.adoc
Labels: unplanned

#3964 stolostron/backlog#24637 add rclone restic fips
  add-ons/volsync/volsync.adoc
  add-ons/volsync/volsync_replicate.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#4024 updating internal links by adding anchor
  governance/cert_policy_ctrl.adoc
  governance/config_policy_ctrl.adoc
  governance/create_config_pol.adoc
  governance/etcd_encryption_policy.adoc
  governance/memory_policy.adoc
  governance/namespace_policy.adoc
  governance/pod_policy.adoc
  governance/psp_policy.adoc
  governance/rolebinding_policy.adoc
  governance/scc_policy.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#4028 adding external functions
  governance/custom_template.adoc
Labels: lgtm

#4030 Updating links
  applications/deployment_rollout.adoc
  multicluster_engine/credentials/credential_on_prem.adoc
  multicluster_engine/install_upgrade/uninstall.adoc
  observability/manage_insights.adoc
  release_notes/known_issues.adoc
  troubleshooting/troubleshooting_intro.adoc
Labels: lgtm

#4008 mce: update install and troubleshooting sections
  multicluster_engine/install_upgrade/install_connected.adoc
  multicluster_engine/install_upgrade/install_disconnected.adoc
  multicluster_engine/support_troubleshooting/trouble_install_status_mce.adoc
  multicluster_engine/support_troubleshooting/trouble_reinstall_mce.adoc
Labels: lgtm

#4036 no issue - add Oliver to owners list
  OWNERS
Labels: do-not-merge/invalid-owners-file

#4035 stolostron/backlog#25386 add conref
  multicluster_engine/install_upgrade/install_connected.adoc
  multicluster_engine/install_upgrade/install_disconnected.adoc
  multicluster_engine/support_troubleshooting/trouble_install_status_mce.adoc
  multicluster_engine/support_troubleshooting/trouble_reinstall_mce.adoc
Labels: lgtm

#3933 pr update due to moved files PR#3874
  multicluster_engine/hosted_control_planes/hosted_control_planes_configure.adoc
Labels: lgtm

#4031 Fix apiVersion in MultiClusterEngine examples
  multicluster_engine/install_upgrade/adv_config_install.adoc
Labels: lgtm

#4045 Updates from meeting review No issue
  release_notes/whats_new.adoc
Labels: lgtm

#4046 Add known issue console in 2.6
  release_notes/known_issues.adoc
Labels: lgtm

#4049 Add console overview known issue 2.6
  release_notes/known_issues.adoc
Labels: lgtm

#4014 Document addition of Hypershift clusters in 2.6
  multicluster_engine/cluster_lifecycle/create_hosted.adoc
  multicluster_engine/cluster_lifecycle/create_intro.adoc
  multicluster_engine/cluster_lifecycle/main.adoc
Labels: lgtm

#4025 Horizontal scaling of ocp cluster in 2.6
  multicluster_engine/cluster_lifecycle/add_hosts_infra_env.adoc
Labels: lgtm

#4050 Add blog link and minor fixes
  _includes/projects.html
  _includes/projects_horizontal.html
  _projects/19_project.md
  _projects/20_project.md
  assets/img/20-publishblog.png
  assets/pdf/example_pdf.pdf
Labels: lgtm

#4051 link fixes
  add-ons/submariner/submariner_deploy_mcaddon_api.adoc
  multicluster_engine/cluster_lifecycle/cluster_proxy_addon.adoc
  multicluster_engine/cluster_lifecycle/create_azure.adoc
  multicluster_engine/cluster_lifecycle/create_google.adoc
  multicluster_engine/cluster_lifecycle/create_ocp_aws.adoc
  multicluster_engine/cluster_lifecycle/create_openstack.adoc
  multicluster_engine/cluster_lifecycle/create_virtualization.adoc
  multicluster_engine/cluster_lifecycle/create_vm.adoc
  release_notes/known_issues.adoc
Labels: lgtm

#4054 Refresh Post GA
  about/supported_providers.adoc
  add-ons/submariner/submariner_deploy_mcaddon_api.adoc
  governance/config_policy_ctrl.adoc
  governance/create_gatekeeper.adoc
  governance/memory_policy.adoc
  governance/namespace_policy.adoc
  governance/pod_policy.adoc
  governance/policy_intro.adoc
  governance/psp_policy.adoc
  governance/rolebinding_policy.adoc
  governance/scc_policy.adoc
  install/requirements.adoc
  multicluster_engine/cluster_lifecycle/add_hosts_infra_env.adoc
  multicluster_engine/cluster_lifecycle/cluster_proxy_addon.adoc
  multicluster_engine/cluster_lifecycle/create_azure.adoc
  multicluster_engine/cluster_lifecycle/create_google.adoc
  multicluster_engine/cluster_lifecycle/create_hosted.adoc
  multicluster_engine/cluster_lifecycle/create_intro.adoc
  multicluster_engine/cluster_lifecycle/create_ocp_aws.adoc
  multicluster_engine/cluster_lifecycle/create_openstack.adoc
  multicluster_engine/cluster_lifecycle/create_virtualization.adoc
  multicluster_engine/cluster_lifecycle/create_vm.adoc
  multicluster_engine/cluster_lifecycle/main.adoc
  multicluster_engine/install_upgrade/adv_config_install.adoc
  multicluster_engine/install_upgrade/install_disconnected.adoc
  release_notes/known_issues.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#4057 Refresh 9/8/22 3
  multicluster_engine/main.adoc
Labels: lgtm

#4058 Test link
  release_notes/whats_new.adoc
Labels: lgtm

#4053 New known issue console alert 2.6
  release_notes/known_issues.adoc
Labels: lgtm

#4060 Refresh link test 9/9/22
  release_notes/known_issues.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#4063 Add missing tech preview
  clusters/scale_managed.adoc
Labels: lgtm

#4064 Add missing tech preview
  multicluster_engine/cluster_lifecycle/scale_managed.adoc
Labels: lgtm

#4062 stolostron/backlog#25676 link improvement
  about/architecture.adoc
  about/quick_start.adoc
  about/supported_providers.adoc
  access_control/rbac.adoc
  applications/ansible_config.adoc
  applications/gitops_config.adoc
  applications/manage_apps_git.adoc
  clusters/cluster_lifecycle_intro.adoc
  console/console.adoc
  governance/ansible_grc.adoc
  governance/policy_intro.adoc
  governance/secure_rhacm.adoc
  governance/security_overview.adoc
  install/uninstall.adoc
  install/upgrade_hub.adoc
  release_notes/deprecate_remove.adoc
  release_notes/whats_new.adoc
  troubleshooting/trouble_auto_import_secret_exists.adoc
  troubleshooting/trouble_cluster_import_kubectl.adoc
  troubleshooting/trouble_console_status.adoc
  troubleshooting/troubleshooting_intro.adoc
Labels: lgtm

#4071 stolostron/backlog#25699 Add errata for 2.6.1
  release_notes/errata.adoc
Labels: lgtm

#4079 Refresh 2.6
  clusters/cluster_lifecycle_intro.adoc
  multicluster_engine/cluster_lifecycle/create_cluster_cli.adoc
  multicluster_engine/cluster_lifecycle/scale_managed.adoc
  release_notes/errata.adoc
  release_notes/known_issues.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#4083 Refresh 2 09/13/22
  release_notes/known_issues.adoc
Labels: lgtm

#4066 Add installation known issue in 2.6
  release_notes/known_issues.adoc
Labels: lgtm

#4091 Hypershift details in 2.6
  multicluster_engine/hosted_control_planes/hosted_control_planes_configure.adoc
Labels: lgtm

#4088 Adding new row to Managed cluster networking requirements
  install/requirements.adoc
Labels: lgtm

#4084 Remove manual OpenStack deploy in 2.6
  add-ons/submariner/submariner.adoc
  add-ons/submariner/submariner_prepare_hosts.adoc
Labels: lgtm

#4087 Clarify Submariner steps 2.5
  add-ons/submariner/submariner_deploy_mcaddon_api.adoc
Labels: lgtm

#4101 Refresh link fixes 09/15/22
  add-ons/submariner/submariner.adoc
  add-ons/submariner/submariner_deploy_mcaddon_api.adoc
  add-ons/submariner/submariner_prepare_hosts.adoc
  governance/kyverno_add_network_policy.adoc
  governance/kyverno_add_quota_policy.adoc
  governance/kyverno_sync_secrets_policy.adoc
  governance/main.adoc
  governance/policy_sample_intro.adoc
  install/requirements.adoc
  multicluster_engine/cluster_lifecycle/create_hosted.adoc
  multicluster_engine/hosted_control_planes/hosted_control_planes_configure.adoc
  release_notes/known_issues.adoc
Labels: lgtm

#4113 Security fix
  _pages/cheat_logins.md
Labels: lgtm

#4115 New card + link fix
  _pages/arch_builds.md
  _projects/21_project.md
  assets/img/21-shortenurl.png
Labels: lgtm

#4116 Clarify connected vs. disconnected environment
  multicluster_engine/cluster_lifecycle/create_infra_env.adoc
Labels: lgtm

#4103 change version create cluster
  multicluster_engine/cluster_lifecycle/create_cluster_cli.adoc
Labels: lgtm

#4118 No issue, scrum discussion
  release_notes/release_notes.adoc
Labels: lgtm

#4120 stolostron/backlog#24696--changes from meeting and review
  install/adv_config_install.adoc
  multicluster_engine/hosted_control_planes/hosted_control_planes_configure.adoc
  multicluster_engine/install_upgrade/adv_config_install.adoc
Labels: lgtm

#4107 Add GRC config policy metric in 2.6
  governance/governance_metric.adoc
  observability/observe_environments.adoc
Labels: lgtm, do-not-merge/hold

#4126 2.6 refresh
  governance/governance_metric.adoc
  install/adv_config_install.adoc
  multicluster_engine/cluster_lifecycle/create_cluster_cli.adoc
  multicluster_engine/cluster_lifecycle/create_infra_env.adoc
  multicluster_engine/cluster_lifecycle/import.adoc
  multicluster_engine/cluster_lifecycle/import_cli.adoc
  multicluster_engine/cluster_lifecycle/import_gui.adoc
  multicluster_engine/hosted_control_planes/hosted_control_planes_configure.adoc
  multicluster_engine/install_upgrade/adv_config_install.adoc
  observability/observe_environments.adoc
  release_notes/known_issues.adoc
  release_notes/release_notes.adoc
  troubleshooting/must_gather.adoc
Labels: lgtm

#4127 2.5 refresh
  add-ons/submariner/submariner.adoc
  add-ons/submariner/submariner_deploy_mcaddon_api.adoc
  add-ons/submariner/submariner_prepare_hosts.adoc
  clusters/create_infra_env.adoc
  governance/kyverno_add_network_policy.adoc
  governance/kyverno_add_quota_policy.adoc
  governance/kyverno_sync_secrets_policy.adoc
  governance/main.adoc
  governance/policy_sample_intro.adoc
  install/requirements.adoc
  multicluster_engine/cluster_create_cli.adoc
  release_notes/errata.adoc
  release_notes/known_issues.adoc
Labels: lgtm

#3129 (SAVE FOR 2.6 PLANNING SPRINT) Add GHA to test AsciiDoc builds on each PR
  .github/workflows/linting.yml
Labels: lgtm

#4132 Refresh for 2.4.6 GA and errata 09/26/22
  clusters/import_gui.adoc
  clusters/proxy.adoc
  observability/customize_observability.adoc
  release_notes/deprecate_remove.adoc
  release_notes/errata.adoc
  troubleshooting/main.adoc
  troubleshooting/trouble_already_exists.adoc
Labels: lgtm

#4144 Fix link in MCE intro
  multicluster_engine/cluster_lifecycle/cluster_lifecycle_intro.adoc
Labels: lgtm

#4122 stolostron/backlog#24460 Add pull secret 2.5
  clusters/import_cli.adoc
  clusters/import_gui.adoc
  multicluster_engine/import_cli.adoc
Labels: lgtm

#4105 Add GitHub issue point guide
  _pages/arch_points.md
  _pages/dropdown2.md
Labels: lgtm

#4139 Enable assisted on AWS in 2.5
  clusters/create_infra_env.adoc
Labels: lgtm

#4146 stolostron/backlog#26000 Add 2.4.7 errata
  release_notes/errata.adoc
Labels: lgtm

#4133 Add new bind role 2.6
  access_control/rbac.adoc
Labels: lgtm

#4151 Refresh for 2.4.7 emerg fix 9/28/22
  release_notes/errata.adoc
Labels: lgtm

#4142 moving the search in the console topic to observability
  applications/app_console.adoc
  console/console.adoc
  console/console_intro.adoc
  console/main.adoc
  install/perform_scale.adoc
  observability/main.adoc
  observability/observe_environments_intro.adoc
  observability/search.adoc
Labels: lgtm

#4098 stolostron/backlog#25015 hosted fixes
  multicluster_engine/hosted_control_planes/hosted_control_planes_configure.adoc
Labels: lgtm

#4149 Document do-not-delete annotation in 2.6
  applications/manage_apps_git.adoc
  applications/manage_apps_helm.adoc
  applications/manage_apps_object.adoc
Labels: do-not-merge/hold
