Repository stolostron/rhacm-docs, pull requests merged in 2023-09, with the labels that each got.

#5456 changed source to sources https://issues.redhat.com/browse/ACM-6811
  applications/app_model.adoc
  gitops/gitops_push_pull.adoc
Labels: lgtm

#5464 https://issues.redhat.com/browse/ACM-7277 Errata 2.6.7
  release_notes/errata.adoc
Labels: lgtm

#5467 Refresh for ACM 2.6.7 and MCE 2.1.8 z-stream 9/05/23
  release_notes/errata.adoc
Labels: lgtm

#5463 https://issues.redhat.com/browse/ACM-6709 Add spec option
  governance/config_policy_ctrl.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#5469 [ACM-4437]: Clarifying steps to import a managed cluster
  multicluster_engine/cluster_lifecycle/import_cli.adoc
Labels: lgtm

#5468 https://issues.redhat.com/browse/ACM-7251 Add SNO note
  clusters/install_upgrade/adv_config_install.adoc
Labels: lgtm

#5483 Refresh of 2.8 9/07/23
  install/adv_config_install.adoc
  release_notes/known_issues_intro.adoc
Labels: lgtm

#5480 modified oc adm command
  clusters/support_troubleshooting/must_gather_mce.adoc
  troubleshooting/must_gather.adoc
Labels: lgtm

#5479 modified oc adm command
  clusters/support_troubleshooting/must_gather_mce.adoc
  troubleshooting/must_gather.adoc
Labels: lgtm

#5478 modified oc adm command
  clusters/support_troubleshooting/must_gather_mce.adoc
  troubleshooting/must_gather.adoc
Labels: lgtm

#5477 modified oc adm command
  troubleshooting/must_gather.adoc
Labels: lgtm

#5475 fixed typo for 2.8
  governance/opp_policyset_install.adoc
Labels: lgtm

#5474 fixed typo
  governance/opp_policyset_install.adoc
Labels: lgtm

#5471 Adding release note to state that hosted control planes is enabled by default
  clusters/release_notes/whats_new.adoc
Labels: lgtm

#5489 Fixing links and reorganizing manual import topics for hosted control planes
  clusters/hosted_control_planes/configure_hosted_aws.adoc
  clusters/hosted_control_planes/importing_hosted_cluster_aws.adoc
  clusters/hosted_control_planes/managing_hosted_aws.adoc
  clusters/main.adoc
Labels: lgtm

#5472 [ACM-6950][ACM-7345] Update advanced config install
  install/adv_config_install.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#5503 added known issue for topology argo cd pull model
  release_notes/known_issues_application.adoc
Labels: lgtm

#5501 https://issues.redhat.com/browse/ACM-7071 Remove API 2.9
  release_notes/deprecate_remove.adoc
Labels: lgtm

#5494 [ACM-7383]: Clarifying what HOSTED_CONTROL_PLANE_NAMESPACE refers to
  clusters/hosted_control_planes/hosted_bare_metal_infraenv.adoc
Labels: lgtm

#5515 Updating Log into to Log in to
  applications/manage_apps_object.adoc
  clusters/cluster_lifecycle/create_infra_env.adoc
  clusters/hosted_control_planes/hosting_service_cluster_access.adoc
  gitops/gitops_manage_policy_def.adoc
  governance/ansible_grc.adoc
  governance/create_config_pol.adoc
  governance/create_gatekeeper.adoc
  governance/create_policy.adoc
  observability/manage_insights.adoc
Labels: lgtm

#5517 Refresh 09/14/23
  apis/api.adoc
  apis/main.adoc
  apis/managedclusterset.json.adoc
  business_continuity/backup_restore/backup_intro.adoc
  clusters/cluster_lifecycle/create_infra_env.adoc
  clusters/release_notes/known_issues.adoc
  clusters/support_troubleshooting/must_gather_mce.adoc
  governance/adv_template_process.adoc
  governance/opp_policyset_install.adoc
  troubleshooting/must_gather.adoc
Labels: lgtm

#5510 https://issues.redhat.com/browse/ACM-7175 remove self-managed note 28
  applications/app_model.adoc
Labels: lgtm

#5523 Swope monitoring
  health_metrics/using_metrics.adoc
Labels: lgtm, needs-rebase

#5531 https://issues.redhat.com/browse/ACM-7517 Update adv_config_install.adoc
  clusters/install_upgrade/adv_config_install.adoc
Labels: lgtm

#5528 Swope mce
  clusters/install_upgrade/adv_config_install.adoc
Labels: needs-rebase

#5513 updating what's new
  clusters/release_notes/whats_new.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#5534 [ACM-7629]: Updating example versions for KubeVirt
  clusters/hosted_control_planes/configuring_storage_kubevirt.adoc
  clusters/hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc
  clusters/hosted_control_planes/create_hosted_clusters_kubevirt_scaling_node_pool.adoc
  clusters/hosted_control_planes/creating_a_hosted_cluster_kubevirt.adoc
  clusters/hosted_control_planes/handling_ingress_hosted.adoc
  clusters/hosted_control_planes/hosting_service_cluster_configure_metallb.adoc
  clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
Labels: lgtm

#5519 [ACM-7527]: Adding note about flags in command to create a hosted cluster
  clusters/hosted_control_planes/configure_hosted_aws.adoc
  clusters/hosted_control_planes/create_hosted_aws.adoc
  clusters/hosted_control_planes/hosted_install_cli.adoc
  clusters/hosted_control_planes/hosting_service_cluster_access.adoc
  clusters/hosted_control_planes/managing_hosted_aws.adoc
  clusters/main.adoc
Labels: lgtm

#5541 [ACM-6433]: Removing section about HyperShift add-on
  clusters/install_upgrade/adv_config_install.adoc
Labels: lgtm

#5522 https://issues.redhat.com/browse/ACM-7111 Train 06 agent reg API
  apis/api.adoc
  apis/klusterletconfig.json.adoc
  apis/main.adoc
  clusters/cluster_lifecycle/import.adoc
  clusters/cluster_lifecycle/import_agent.adoc
  clusters/cluster_lifecycle/import_cli.adoc
  clusters/cluster_lifecycle/import_gui.adoc
  clusters/cluster_lifecycle/specify_img_registry.adoc
  clusters/hosted_control_planes/creating_a_hosted_cluster_kubevirt.adoc
  clusters/main.adoc
Labels: lgtm

#5545 2.7.8/2.2.8 errata
  clusters/release_notes/errata.adoc
  release_notes/errata.adoc
Labels: lgtm

#5551 https://issues.redhat.com/browse/ACM-7660 updating the FIPS statement
  release_notes/fips_readiness.adoc
Labels: lgtm

#5549 https://issues.redhat.com/browse/ACM-7743 Fix links
  business_continuity/backup_restore/backup_install.adoc
  business_continuity/backup_restore/backup_intro.adoc
Labels: lgtm

#5550 https://issues.redhat.com/browse/ACM-7743 Fix backup and restore link…
  business_continuity/backup_restore/backup_install.adoc
  business_continuity/backup_restore/backup_intro.adoc
Labels: lgtm

#5557 Refresh 9/28/23 2.8
  apis/api.adoc
  apis/main.adoc
  apis/search.json.adoc
  applications/app_model.adoc
  business_continuity/backup_restore/backup_install.adoc
  business_continuity/backup_restore/backup_intro.adoc
  clusters/cluster_lifecycle/create_cluster_on_prem.adoc
  clusters/cluster_lifecycle/create_infra_env.adoc
  clusters/install_upgrade/adv_config_install.adoc
  clusters/release_notes/known_issues.adoc
  clusters/release_notes/whats_new.adoc
  governance/gatekeeper_policy.adoc
  health_metrics/using_metrics.adoc
  install/perform_scale.adoc
Labels: lgtm

#5556 Refresh 9/28/23 2.7
  apis/api.adoc
  apis/main.adoc
  apis/managedclusterset.json.adoc
  apis/search.json.adoc
  applications/app_model.adoc
  clusters/cluster_lifecycle/create_infra_env.adoc
  clusters/install_upgrade/adv_config_install.adoc
  clusters/release_notes/errata.adoc
  clusters/release_notes/known_issues.adoc
  clusters/support_troubleshooting/must_gather_mce.adoc
  governance/gatekeeper_policy.adoc
  install/perform_scale.adoc
  release_notes/errata.adoc
  troubleshooting/must_gather.adoc
Labels: lgtm

#5561 Refresh 9/29/23 2.6
  multicluster_engine/cluster_lifecycle/import_cli.adoc
  troubleshooting/main.adoc
  troubleshooting/must_gather.adoc
  troubleshooting/trouble_oadp_crd.adoc
  troubleshooting/troubleshooting_intro.adoc
Labels: lgtm

#5543 Swope known issue (3)
  release_notes/known_issues.adoc
Labels: lgtm

#5564 Swope known3
  release_notes/known_issues_continuity.adoc
Labels: needs-rebase
