Repository stolostron/rhacm-docs, pull requests merged in 2023-05, with the labels that each got.

#4998 Updating function example
  governance/template_functions.adoc
Labels: lgtm

#5011 https://issues.redhat.com/browse/ACM-3383--move topics, redo descript…
  about/docinfo.xml
  access_control/docinfo.xml
  add-ons/docinfo.xml
  add-ons/main.adoc
  apis/docinfo.xml
  applications/docinfo.xml
  backup_restore/main.adoc
  business_continuity/backup_restore/backup_activation.adoc
  business_continuity/backup_restore/backup_adv_config.adoc
  business_continuity/backup_restore/backup_arch.adoc
  business_continuity/backup_restore/backup_hub_config.adoc
  business_continuity/backup_restore/backup_install.adoc
  business_continuity/backup_restore/backup_intro.adoc
  business_continuity/backup_restore/backup_msa.adoc
  business_continuity/backup_restore/backup_restore.adoc
  business_continuity/backup_restore/backup_schedule.adoc
  business_continuity/backup_restore/backup_validate.adoc
  business_continuity/docinfo.xml
  business_continuity/main.adoc
  business_continuity/master.adoc
  business_continuity/modules
  business_continuity/volsync/adv_config_volsync.adoc
  business_continuity/volsync/volsync.adoc
  business_continuity/volsync/volsync_convert_backup.adoc
  business_continuity/volsync/volsync_replicate.adoc
  business_continuity/volsync/volsync_schedule.adoc
  clusters/docinfo.xml
  console/docinfo.xml
  governance/docinfo.xml
  install/docinfo.xml
  networking/docinfo.xml
  networking/main.adoc
  networking/submariner/deploy_subm_console.adoc
  networking/submariner/deploy_subm_manual.adoc
  networking/submariner/install_subctl.adoc
  networking/submariner/service_discovery.adoc
  networking/submariner/subm_configure.adoc
  networking/submariner/subm_customize.adoc
  networking/submariner/subm_disconnected.adoc
  networking/submariner/subm_intro.adoc
  networking/submariner/uninstall_subm.adoc
  observability/docinfo.xml
  release_notes/docinfo.xml
  troubleshooting/docinfo.xml
Labels: lgtm

#4986 Add deprecation note for Gatekeeper in generator
  governance/policy_generator.adoc
Labels: lgtm

#4922 2.6.5 docs errata
  release_notes/errata.adoc
Labels: lgtm

#5022 Add label selector to `lookup` template documentation
  governance/template_functions.adoc
Labels: lgtm

#5027 Add back removed known issue
  release_notes/known_issues.adoc
Labels: lgtm

#5033 2.5 errata refresh
  release_notes/errata.adoc
Labels: lgtm

#4987 Search metrics 2.8
  observability/observe_environments.adoc
  observability/observe_environments_intro.adoc
  observability/search_intro.adoc
  release_notes/whats_new.adoc
Labels: do-not-merge/hold

#5036 Refresh 2.7 5/4/23
  observability/customize_observability.adoc
  release_notes/errata.adoc
  release_notes/known_issues.adoc
Labels: lgtm

#5041 https://issues.redhat.com/browse/ACM-4965 Credential update
  clusters/credentials/credential_aws.adoc
  clusters/credentials/credential_azure.adoc
  clusters/credentials/credential_google.adoc
  clusters/credentials/credential_openstack.adoc
  clusters/credentials/credential_vm.adoc
Labels: lgtm

#5010 update the hypershift agent doc for ACM-4277
  clusters/hosted_control_planes/managing_hosted_bm.adoc
Labels: lgtm

#5059 Swope release
  clusters/cluster_lifecycle/cluster_lifecycle_intro.adoc
Labels: needs-rebase

#5066 https://issues.redhat.com/browse/ACM-5306
  release_notes/known_issues_network.adoc
Labels: lgtm

#5069 https://issues.redhat.com/browse/ACM-4181 -- bug console
  install/install_connected.adoc
Labels: lgtm

#5042 acm4773 remove known issues
  release_notes/known_issues_application.adoc
  release_notes/known_issues_console.adoc
  release_notes/known_issues_continuity.adoc
  release_notes/known_issues_governance.adoc
  release_notes/known_issues_install.adoc
  release_notes/known_issues_intro.adoc
  release_notes/known_issues_network.adoc
  release_notes/known_issues_observability.adoc
Labels: lgtm

#4956 add addon to apis
  apis/addondeploymentconfig.json.adoc
  apis/clustermanagementaddon.json.adoc
  apis/main.adoc
  apis/managedclusteraddon.json.adoc
  apis/placement.json.adoc
Labels: lgtm

#5076 No Jira: Restructuring AWS files to reduce file length
  clusters/hosted_control_planes/deploying_aws_private_clusters.adoc
  clusters/hosted_control_planes/managing_hosted_aws.adoc
  clusters/main.adoc
Labels: lgtm

#5080 Update GRC policy flapping known issue
  release_notes/known_issues.adoc
Labels: lgtm

#5084 https://issues.redhat.com/browse/ACM-5559 : add .yaml callout
  add-ons/klusterlet_managed.adoc
Labels: lgtm

#5085 https://issues.redhat.com/browse/ACM-5559 : add .yaml callout
  add-ons/cluster_wide_proxy.adoc
Labels: lgtm

#5086 https://issues.redhat.com/browse/ACM-5559 add .yaml callout
  applications/package_overrides.adoc
Labels: lgtm

#5087 https://issues.redhat.com/browse/ACM-5559 add .yaml callout
  business_continuity/volsync/volsync_replicate.adoc
Labels: lgtm

#5088 2.7 stage
  clusters/cluster_lifecycle/cluster_lifecycle_intro.adoc
  clusters/cluster_lifecycle/create_aws_govcloud.adoc
  clusters/cluster_lifecycle/create_azure.adoc
  clusters/cluster_lifecycle/create_cluster_on_prem.adoc
  clusters/cluster_lifecycle/create_google.adoc
  clusters/cluster_lifecycle/create_ocp_aws.adoc
  clusters/cluster_lifecycle/create_openstack.adoc
  clusters/cluster_lifecycle/create_virtualization.adoc
  clusters/cluster_lifecycle/create_vm.adoc
  clusters/cluster_lifecycle/release_image_connected.adoc
  clusters/cluster_lifecycle/release_image_disconn.adoc
  clusters/cluster_lifecycle/release_image_intro.adoc
  clusters/cluster_lifecycle/release_images.adoc
  clusters/cluster_lifecycle/release_images_specify.adoc
  clusters/cluster_mce_overview.adoc
  clusters/credentials/credential_aws.adoc
  clusters/credentials/credential_azure.adoc
  clusters/credentials/credential_google.adoc
  clusters/credentials/credential_openstack.adoc
  clusters/credentials/credential_vm.adoc
  clusters/install_upgrade/install_intro.adoc
  clusters/install_upgrade/upgrade_cluster.adoc
  clusters/install_upgrade/upgrade_cluster_disconnected.adoc
  clusters/main.adoc
  clusters/support_troubleshooting/troubleshooting_mce_intro.adoc
  release_notes/known_issues.adoc
Labels: lgtm

#5089 https://issues.redhat.com/browse/ACM-5559 yaml callout
  clusters/cluster_lifecycle/cluster_pool_create.adoc
Labels: lgtm

#4846 Swope 13 WIP-do not merge
  apis/policy.json.adoc
  health_metrics/docinfo.xml
  health_metrics/health_intro.adoc
  health_metrics/main.adoc
  health_metrics/master.adoc
  health_metrics/master.html
  health_metrics/modules
  health_metrics/using_metrics.adoc
  troubleshooting/main.adoc
  troubleshooting/trouble_metric_no_hub.adoc
  troubleshooting/trouble_metric_no_managed.adoc
  troubleshooting/trouble_metric_no_standalone.adoc
  troubleshooting/trouble_restore_status.adoc
  troubleshooting/troubleshooting_intro.adoc
Labels: lgtm

#5091 https://issues.redhat.com/browse/ACM-5559 add .yaml callout
  business_continuity/volsync/volsync_replicate.adoc
Labels: lgtm

#5092 Swope yaml fix bold space
  health_metrics/using_metrics.adoc
Labels: needs-rebase

#4996 acm2927 add link to Discovery ISO kernel args 2.8
  clusters/cluster_lifecycle/create_infra_env.adoc
Labels: lgtm

#5040 https://issues.redhat.com/browse/ACM-5024 Gatekeeper operator updates
  governance/create_gatekeeper.adoc
  release_notes/deprecate_remove.adoc
Labels: lgtm

#5109 https://issues.redhat.com/browse/ACM-5545 2.7.4 errata
  release_notes/errata.adoc
Labels: lgtm

#5078 [ACM-4126]: Adding docs about creating a hosted cluster in multiple AWS zones
  clusters/hosted_control_planes/managing_hosted_aws.adoc
Labels: lgtm

#5096 acm5401 upd link to clusterimageset 2.8/2.3
  clusters/cluster_lifecycle/create_cluster_cli.adoc
Labels: lgtm

#5123 https://issues.redhat.com/browse/ACM-5166 correcting navigation steps and removing yaml references
  clusters/hosted_control_planes/managing_hosted_aws.adoc
Labels: lgtm

#5124 https://issues.redhat.com/browse/ACM-5621 2.6.6
  release_notes/errata.adoc
Labels: lgtm

#5101 acm1479 changing storage partition on node
  clusters/cluster_lifecycle/create_infra_env.adoc
Labels: lgtm

#4970 acm4471 add disco clust upgr policy 2.8
  about/architecture.adoc
  clusters/cluster_mce_overview.adoc
  install/install_overview.adoc
  install/main.adoc
  install/upgrade_cluster_disconnected_policies.adoc
  troubleshooting/troubleshooting_intro.adoc
Labels: lgtm

#5132 2.7 refresh
  apis/policy.json.adoc
  clusters/cluster_lifecycle/create_cluster_cli.adoc
  clusters/cluster_lifecycle/create_infra_env.adoc
  clusters/hosted_control_planes/managing_hosted_bm.adoc
  clusters/release_notes/errata.adoc
  health_metrics/docinfo.xml
  health_metrics/health_intro.adoc
  health_metrics/main.adoc
  health_metrics/master.adoc
  health_metrics/master.html
  health_metrics/modules
  health_metrics/using_metrics.adoc
  observability/customize_observability.adoc
  release_notes/errata.adoc
  release_notes/known_issues.adoc
  troubleshooting/main.adoc
  troubleshooting/trouble_metric_no_hub.adoc
  troubleshooting/trouble_metric_no_managed.adoc
  troubleshooting/trouble_metric_no_standalone.adoc
  troubleshooting/trouble_restore_status.adoc
  troubleshooting/troubleshooting_intro.adoc
Labels: lgtm

#5131 2.6 refresh
  observability/customize_observability.adoc
  release_notes/errata.adoc
Labels: lgtm

#5114 https://issues.redhat.com/browse/ACM-4942 Obs KI 2.8
  release_notes/known_issues_observability.adoc
Labels: lgtm

#5144 2.5 refresh
  observability/customize_observability.adoc
  release_notes/errata.adoc
Labels: lgtm
