Repository stolostron/rhacm-docs, pull requests merged in 2023-10, with the labels that each got.

#5577 https://issues.redhat.com/browse/ACM-7645 MCE 2.3.2 Errata
  clusters/release_notes/errata.adoc
Labels: lgtm

#5552 https://issues.redhat.com/browse/ACM-7523 Deprecate MSA API 2.9
  clusters/api/managed_serviceaccount.json.adoc
  clusters/api/multicluster_engine.json.adoc
  clusters/release_notes/deprecate_remove.adoc
  clusters/release_notes/known_issues.adoc
Labels: lgtm

#5600 2.8 Refresh build fix on 10/6 to 10/8
  business_continuity/backup_restore/backup_msa.adoc
  clusters/support_troubleshooting/troubleshooting_mce_intro.adoc
Labels: lgtm

#5606 changed notes for 2.7
  backup_restore/manage_backup_restore.adoc
Labels: lgtm

#5576 modified notes
  business_continuity/backup_restore/backup_install.adoc
Labels: lgtm

#5586 https://issues.redhat.com/browse/ACM-7680 Add backup collision topic
  business_continuity/backup_restore/backup_schedule.adoc
  business_continuity/backup_restore/backup_validate.adoc
  release_notes/known_issues_continuity.adoc
Labels: lgtm

#5613 https://issues.redhat.com/browse/ACM-7893 Removing Kyverno policies
  governance/kyverno_add_network_policy.adoc
  governance/kyverno_add_quota_policy.adoc
  governance/kyverno_sync_secrets_policy.adoc
  governance/main.adoc
  governance/policy_generator.adoc
  governance/supported_policies.adoc
Labels: lgtm

#5617 ACM-7909: add a note about uniqueness of hosted cluster names
  clusters/hosted_control_planes/managing_hosted_aws.adoc
  clusters/hosted_control_planes/managing_hosted_bm.adoc
  clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
Labels: lgtm

#5619 modified description and added link
  business_continuity/backup_restore/backup_activation.adoc
  business_continuity/backup_restore/backup_restore.adoc
Labels: lgtm

#5630 2.6 Refresh build fix on 10/13
  governance/kyverno_add_network_policy.adoc
  governance/kyverno_add_quota_policy.adoc
  governance/kyverno_sync_secrets_policy.adoc
  governance/main.adoc
  governance/policy_generator.adoc
  governance/policy_sample_intro.adoc
Labels: lgtm

#5629 2.7 Refresh build fix on 10/13
  backup_restore/manage_backup_restore.adoc
  clusters/support_troubleshooting/trouble_network_config_bm.adoc
  governance/kyverno_add_network_policy.adoc
  governance/kyverno_add_quota_policy.adoc
  governance/kyverno_sync_secrets_policy.adoc
  governance/main.adoc
  governance/policy_generator.adoc
  governance/supported_policies.adoc
  release_notes/known_issues.adoc
Labels: lgtm

#5628 2.8 Refresh build fix on 10/13
  business_continuity/backup_restore/backup_install.adoc
  business_continuity/backup_restore/backup_schedule.adoc
  business_continuity/backup_restore/backup_validate.adoc
  clusters/support_troubleshooting/trouble_network_config_bm.adoc
  governance/cert_policy_ctrl.adoc
  governance/compliance_operator_policy.adoc
  governance/config_policy_ctrl.adoc
  governance/create_config_pol.adoc
  governance/create_gatekeeper.adoc
  governance/create_policy.adoc
  governance/deploy_gitops.adoc
  governance/e8_scan_policy.adoc
  governance/etcd_encryption_policy.adoc
  governance/grc_intro.adoc
  governance/iam_policy_ctrl.adoc
  governance/image_vuln_policy.adoc
  governance/kyverno_add_network_policy.adoc
  governance/kyverno_add_quota_policy.adoc
  governance/kyverno_sync_secrets_policy.adoc
  governance/main.adoc
  governance/memory_policy.adoc
  governance/namespace_policy.adoc
  governance/ocp_cis_policy.adoc
  governance/opp_policyset_install.adoc
  governance/pod_policy.adoc
  governance/policy_generator.adoc
  governance/policy_set_ctrl.adoc
  governance/psp_policy.adoc
  governance/role_policy.adoc
  governance/rolebinding_policy.adoc
  governance/scc_policy.adoc
  governance/supported_policies.adoc
  governance/third_party_policy.adoc
  release_notes/known_issues_continuity.adoc
Labels: lgtm

#5632 modified shutting down cluster content for 2.7
  backup_restore/manage_backup_restore.adoc
Labels: lgtm

#5637 Swope editing2
  business_continuity/backup_restore/backup_restore.adoc
Labels: needs-rebase

#5640 https://issues.redhat.com/browse/ACM-7875--removing for GRC
  release_notes/known_issues_governance.adoc
  troubleshooting/trouble_cluster_offline_avail.adoc
Labels: lgtm

#5641 https://issues.redhat.com/browse/ACM-7875--removing for GRC2
  release_notes/known_issues_governance.adoc
  troubleshooting/trouble_cluster_offline_avail.adoc
Labels: lgtm

#5612 [ACM-7858]: Adding port limitation and KubeVirt troubleshooting docs
  clusters/hosted_control_planes/create_hosted_clusters_kubevirt_default_ingress_dns.adoc
  clusters/main.adoc
  clusters/support_troubleshooting/trouble_hosted_cluster_ingress_console_not_online.adoc
  clusters/support_troubleshooting/trouble_hosted_cluster_load_balancer.adoc
  clusters/support_troubleshooting/trouble_hosted_cluster_pvcs_not_available.adoc
  clusters/support_troubleshooting/trouble_hosted_cluster_vm_console_logs.adoc
  clusters/support_troubleshooting/trouble_hosted_cluster_worker_nodes_stuck.adoc
  clusters/support_troubleshooting/trouble_hosted_clusters_kubevirt.adoc
  clusters/support_troubleshooting/trouble_hosted_control_plane_no_worker_nodes.adoc
  clusters/support_troubleshooting/trouble_hostedcluster_resource_stuck.adoc
Labels: lgtm

#5605 https://issues.redhat.com/browse/ACM-6522 CIM complete restructure
  clusters/cluster_lifecycle/cim_create_console.adoc
  clusters/cluster_lifecycle/cim_enable.adoc
  clusters/cluster_lifecycle/cim_enable_aws.adoc
  clusters/cluster_lifecycle/cim_import.adoc
  clusters/cluster_lifecycle/cim_intro.adoc
  clusters/main.adoc
Labels: lgtm

#5312 https://issues.redhat.com/browse/ACM-4191 Updating max number of managed clusters
  install/perform_scale.adoc
Labels: lgtm

#5655 Swope cherry pick
  clusters/cluster_lifecycle/import_gui.adoc
Labels: needs-rebase

#5603 https://issues.redhat.com/browse/ACM-7660 Updating FIPS statement, issue reopened
  release_notes/fips_readiness.adoc
Labels: lgtm, do-not-merge/hold

#5585 [ACM-7350]: Troubleshooting docs for hosted control planes
  clusters/main.adoc
  clusters/support_troubleshooting/trouble_hosted_cluster_backplane.adoc
  troubleshooting/main.adoc
  troubleshooting/trouble_hosted_cluster.adoc
Labels: lgtm

#5650 https://issues.redhat.com/browse/ACM-3748 improving the Observability doc mismatched Grafana 2.8
  observability/customize_observability.adoc
  release_notes/known_issues_observability.adoc
Labels: lgtm

#5680 CIM product style guide compliance
  clusters/cluster_lifecycle/cim_create_console.adoc
  clusters/cluster_lifecycle/cim_enable.adoc
  clusters/cluster_lifecycle/cim_enable_aws.adoc
  clusters/cluster_lifecycle/cim_intro.adoc
  clusters/cluster_lifecycle/create_cluster_on_prem.adoc
  clusters/cluster_lifecycle/create_intro.adoc
  clusters/cluster_lifecycle/scale_hosts_infra_env.adoc
  clusters/hosted_control_planes/configure_hosted_bm.adoc
  clusters/release_notes/known_issues.adoc
  clusters/release_notes/whats_new.adoc
  networking/network_advanced.adoc
Labels: lgtm

#5652 added context for ACM installs versions
  business_continuity/backup_restore/backup_intro.adoc
Labels: lgtm

#5653 added context for ACM install versions for 2.8
  business_continuity/backup_restore/backup_intro.adoc
Labels: lgtm

#5694 2.8.3 CVE Errata ACM/MCE
  clusters/release_notes/errata.adoc
  release_notes/errata.adoc
Labels: lgtm

#5693 https://issues.redhat.com/browse/ACM-7411 updating ClusterRole example
  gitops/gitops_manage_policy_def.adoc
Labels: lgtm

#5697 2.7.9 ACM/MCE Errata CVE
  clusters/release_notes/errata.adoc
  release_notes/errata.adoc
Labels: lgtm

#5688 https://issues.redhat.com/browse/ACM-8260
  networking/submariner/subm_customize.adoc
  release_notes/known_issues_network.adoc
Labels: lgtm

#5711 https://issues.redhat.com/browse/ACM-8355 Fix RBAC description
  access_control/rbac_implement_rhacm.adoc
Labels: lgtm

#5691 https://issues.redhat.com/browse/ACM-7770
  business_continuity/backup_restore/backup_install.adoc
Labels: lgtm

#5708 remove tp for 2.8
  business_continuity/backup_restore/backup_restore.adoc
Labels: lgtm

#5707 https://issues.redhat.com/browse/ACM-8332
  business_continuity/backup_restore/backup_restore.adoc
Labels: lgtm

#5714 Refresh 10/27/23 2.7.9 z-stream
  backup_restore/backup_intro.adoc
  clusters/cluster_lifecycle/cim_create_cli.adoc
  clusters/cluster_lifecycle/cim_create_console.adoc
  clusters/cluster_lifecycle/cim_enable.adoc
  clusters/cluster_lifecycle/cim_enable_aws.adoc
  clusters/cluster_lifecycle/cim_intro.adoc
  clusters/cluster_lifecycle/cluster_lifecycle_intro.adoc
  clusters/cluster_lifecycle/create_cluster_on_prem.adoc
  clusters/cluster_lifecycle/create_intro.adoc
  clusters/cluster_lifecycle/scale_hosts_infra_env.adoc
  clusters/hosted_control_planes/configure_hosted_bm.adoc
  clusters/main.adoc
  clusters/release_notes/errata.adoc
  clusters/release_notes/known_issues.adoc
  clusters/release_notes/whats_new.adoc
  networking/network_advanced.adoc
  release_notes/errata.adoc
Labels: lgtm

#5639 https://issues.redhat.com/browse/ACM-5520--2.7
  troubleshooting/trouble_cluster_offline_avail.adoc
Labels: lgtm

#5717 https://issues.redhat.com/browse/ACM-7640 Updating search performance
  install/perform_scale.adoc
Labels: lgtm

#5725 Refresh for ACM 2.6.8 and MCE 2.1.9 10/30/23
  release_notes/errata.adoc
Labels: lgtm

#5728 https://issues.redhat.com/browse/ACM-8416--hcp consistency
  clusters/cluster_lifecycle/ansible_config_hosted_cluster.adoc
  clusters/hosted_control_planes/configure_hosted_aws.adoc
  clusters/hosted_control_planes/configure_hosted_bm.adoc
  clusters/hosted_control_planes/creating_a_hosted_cluster_kubevirt.adoc
  clusters/hosted_control_planes/deploying_aws_private_clusters.adoc
  clusters/hosted_control_planes/hosted-cluster-workload-distributing.adoc
  clusters/hosted_control_planes/hosted_cluster_arm_aws.adoc
  clusters/hosted_control_planes/hosted_deploy_cluster_aws.adoc
  clusters/hosted_control_planes/hosted_install_cli.adoc
  clusters/hosted_control_planes/hosted_intro.adoc
  clusters/hosted_control_planes/managing_hosted_aws.adoc
  clusters/hosted_control_planes/managing_hosted_bm.adoc
  clusters/hosted_control_planes/managing_hosted_kubevirt.adoc
Labels: lgtm
