Repository stolostron/rhacm-docs, pull requests merged in 2023-03, with the labels that each got.

#4775 https://issues.redhat.com/browse/ACM-3364
  release_notes/known_issues.adoc
Labels: lgtm

#4776 2.7 Refresh
  .DS_Store
  EXTERNAL_CONTRIBUTING.adoc
  README.adoc
  add-ons/addon_overview.adoc
  add-ons/cluster_wide_proxy.adoc
  add-ons/klusterlet_managed.adoc
  add-ons/main.adoc
  applications/manage_app_resources.adoc
  backup_restore/backup_intro.adoc
  backup_restore/manage_backup_restore.adoc
  clusters/cluster_lifecycle/create_infra_env.adoc
  clusters/cluster_lifecycle/create_proxy_env.adoc
  clusters/hosted_control_planes/configure_hosted.adoc
  clusters/release_notes/known_issues.adoc
  clusters/release_notes/whats_new.adoc
  governance/config_policy_ctrl.adoc
  governance/create_config_pol.adoc
  governance/create_policy.adoc
  governance/manage_policy_def.adoc
  governance/policy_gen_install_operator.adoc
  governance/policy_set_ctrl.adoc
  governance/third_party_policy.adoc
  release_notes/known_issues.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#4778 Fixing broken link
  clusters/hosted_control_planes/configure_hosted.adoc
Labels: lgtm

#4762 https://issues.redhat.com/browse/ACM-3374
  applications/manage_apps_git.adoc
  applications/manage_apps_object.adoc
Labels: lgtm

#4780 https://issues.redhat.com/browse/ACM-3972 2.7.1
  release_notes/errata.adoc
Labels: lgtm

#4783 2.7.1 errata
  EXTERNAL_CONTRIBUTING.adoc
  applications/manage_apps_git.adoc
  applications/manage_apps_object.adoc
  clusters/hosted_control_planes/configure_hosted.adoc
  clusters/release_notes/errata.adoc
  release_notes/errata.adoc
  release_notes/known_issues.adoc
Labels: lgtm

#4771 https://issues.redhat.com/browse/ACM-3236
  multicluster_engine/support_troubleshooting/trouble_cluster_reimport_fails_mce.adoc
Labels: lgtm

#4747 ACM-3386 move lcl-clst ACM 2 mce
  clusters/install_upgrade/adv_config_install.adoc
  clusters/release_notes/whats_new.adoc
  install/adv_config_install.adoc
Labels: lgtm

#4777 WIP https://issues.redhat.com/browse/ACM-3383--rearranging and editing, a…
  clusters/hosted_control_planes/configure_hosted_aws.adoc
  clusters/hosted_control_planes/configure_hosted_bm.adoc
  clusters/hosted_control_planes/destroy_hosted.adoc
  clusters/hosted_control_planes/disable_hosted.adoc
  clusters/hosted_control_planes/hosted_intro.adoc
  clusters/hosted_control_planes/managing_hosted_aws.adoc
  clusters/hosted_control_planes/managing_hosted_bm.adoc
  clusters/main.adoc
Labels: do-not-merge/work-in-progress

#4790 https://issues.redhat.com/browse/ACM-3383--rearranging and editing, a…
  clusters/hosted_control_planes/hosted_intro.adoc
  clusters/hosted_control_planes/managing_hosted_bm.adoc
Labels: needs-rebase

#4793 https://issues.redhat.com/browse/ACM-3736
  backup_restore/manage_backup_restore.adoc
  release_notes/known_issues.adoc
Labels: lgtm

#4795 Improving steps for custom Grafana boards
  observability/design_grafana.adoc
Labels: lgtm

#4766 Updates for the status events
  release_notes/whats_new.adoc
Labels: lgtm

#4800 fix ACM-4051 disabling the hypershift feature
  clusters/hosted_control_planes/disable_hosted.adoc
Labels: lgtm

#4774 acm2394 upd icsp disco 2.6
  multicluster_engine/cluster_lifecycle/create_infra_env.adoc
  multicluster_engine/install_upgrade/install_disconnected.adoc
Labels: lgtm

#4802 https://issues.redhat.com/browse/ACM-4130 Remove known issue
  release_notes/known_issues.adoc
Labels: lgtm

#4787 [2.7_stage] Update policy generator link to upstream
  governance/policy_generator.adoc
Labels: lgtm

#4808 Update the generator docs
  governance/policy_generator.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#4815 2.7.2 errata https://issues.redhat.com/browse/ACM-4269
  release_notes/errata.adoc
Labels: lgtm

#4819 2.7 prod refresh
  clusters/cluster_lifecycle/scale_machinepool.adoc
  clusters/release_notes/errata.adoc
  clusters/release_notes/whats_new.adoc
  governance/manage_policy_def.adoc
  release_notes/errata.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#4825 Update requirements.adoc small change, no issue
  clusters/about/requirements.adoc
Labels: lgtm

#4826 Update design_grafana.adoc (#4810)
  observability/design_grafana.adoc
Labels: lgtm

#4835 Updating the RHACM version in the APIs
  apis/application.json.adoc
  apis/channels.json.adoc
  apis/cluster.json.adoc
  apis/clusterset.json.adoc
  apis/clustersetbinding.json.adoc
  apis/clusterview.json.adoc
  apis/discoveredcluster.json.adoc
  apis/discoveryconfig.json.adoc
  apis/helmreleases.json.adoc
  apis/observability.json.adoc
  apis/placementdecision.json.adoc
  apis/placementrules.json.adoc
  apis/policy.json.adoc
  apis/search.json.adoc
  apis/subscriptions.json.adoc
Labels: lgtm

#4821 acm3752 ts idrac discovery fails 2.8
  clusters/main.adoc
  clusters/support_troubleshooting/trouble_idrac_discovery_fails_mce.adoc
  clusters/support_troubleshooting/troubleshooting_mce_intro.adoc
Labels: lgtm

#4840 fixing table in API Cluster
  apis/cluster.json.adoc
  clusters/api/api_intro.adoc
  clusters/api/cluster.json.adoc
  clusters/cluster_lifecycle/placement_managed.adoc
Labels: lgtm

#4841 https://issues.redhat.com/browse/ACM-2416--adding to table, links, cl…
  governance/config_policy_ctrl.adoc
  governance/create_config_pol.adoc
  governance/create_gatekeeper.adoc
  governance/create_policy.adoc
  governance/custom_template_functions.adoc
Labels: lgtm

#4850 Swope 2.7 again
  clusters/hosted_control_planes/managing_hosted_aws.adoc
Labels: needs-rebase

#4824 [ACM-4111]: Updates to 'Configuring the hosting cluster on bare metal'
  clusters/hosted_control_planes/configure_hosted_bm.adoc
Labels: lgtm

#4854 Improving observability doc org, arch, and quality
  observability/insights_intro.adoc
  observability/main.adoc
  observability/observe_environments.adoc
  observability/observe_environments_intro.adoc
Labels: lgtm

#4861 2.7 refresh
  backup_restore/backup_intro.adoc
  clusters/about/requirements.adoc
  clusters/cluster_lifecycle/cluster_lifecycle_intro.adoc
  clusters/hosted_control_planes/configure_hosted_aws.adoc
  clusters/hosted_control_planes/hosted_intro.adoc
  clusters/hosted_control_planes/managing_hosted_aws.adoc
  clusters/hosted_control_planes/managing_hosted_bm.adoc
  clusters/main.adoc
  clusters/support_troubleshooting/trouble_idrac_discovery_fails_mce.adoc
  clusters/support_troubleshooting/troubleshooting_mce_intro.adoc
  governance/config_policy_ctrl.adoc
  governance/create_config_pol.adoc
  observability/customize_observability.adoc
  observability/manage_search.adoc
  troubleshooting/main.adoc
  troubleshooting/trouble_restore_status.adoc
  troubleshooting/troubleshooting_intro.adoc
Labels: lgtm

#4862 Update intro
  _pages/getting_started_intro.md
Labels: lgtm

#4859 Updates for multiline YAML strings in templates
  governance/config_policy_ctrl.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#4876 Refresh 03/30/23 2.7
  add-ons/submariner/subm_disconnected.adoc
  add-ons/volsync/volsync_replicate.adoc
  clusters/cluster_lifecycle/scale_managed_intro.adoc
  clusters/hosted_control_planes/managing_hosted_bm.adoc
Labels: lgtm

#4881 Fix link https://issues.redhat.com/browse/ACM-4631
  clusters/scale_managed.adoc
Labels: lgtm
