Repository stolostron/rhacm-docs, pull requests merged in 2024-02, with the labels that each got.

#6091 2.8 stage refresh 01/31/24
  apis/api.adoc
  apis/main.adoc
  apis/searchquery.json.adoc
  business_continuity/backup_restore/backup_restore.adoc
  clusters/about/mce_networking.adoc
  networking/network_advanced.adoc
Labels: lgtm

#6094 changed title
  release_notes/known_issues_observability.adoc
Labels: lgtm

#6082 https://issues.redhat.com/browse/ACM-9161 Expand globalnet docs
  networking/submariner/install_subctl.adoc
  networking/submariner/subm_configure.adoc
  networking/submariner/subm_intro.adoc
Labels: lgtm

#6093 Swope hc change 2.9
  clusters/hosted_control_planes/hosted_intro.adoc
Labels: lgtm

#6084 added info on hubs for note
  business_continuity/backup_restore/backup_validate.adoc
Labels: lgtm

#6101 https://issues.redhat.com/browse/ACM-9274 Add proxy config docs
  clusters/cluster_lifecycle/adv_config_cluster.adoc
  clusters/cluster_lifecycle/cluster_proxy_addon.adoc
  clusters/release_notes/whats_new.adoc
Labels: lgtm

#6107 https://issues.redhat.com/browse/ACM-9737 Errata for ACM 2.7.11
  release_notes/errata.adoc
Labels: lgtm

#6060 Update `PlacementRule` --> `Placement` for GRC
  governance/create_policy.adoc
  governance/opp_policyset_install.adoc
  governance/policy_generator.adoc
  governance/policy_overview.adoc
  governance/policy_set_ctrl.adoc
  governance/role_policy.adoc
Labels: lgtm

#6114 Clarify internal docs
  _pages/create_builds.md
Labels: lgtm

#6110 https://issues.redhat.com/browse/ACM-9681 known issue with Kube/API
  release_notes/known_issues_observability.adoc
Labels: lgtm

#6117 Fixing gov book in 2.10
  governance/policy_overview.adoc
Labels: lgtm

#6120 2.7 stage refresh 02/07-02/08/24
  clusters/release_notes/errata.adoc
  release_notes/errata.adoc
Labels: lgtm

#6119 2.8 stage refresh 02/07-02/08/24
  clusters/release_notes/known_issues.adoc
Labels: lgtm

#6103 minor changes based off dev input
  business_continuity/backup_restore/backup_arch.adoc
Labels: lgtm

#6118 2.9 stage refresh 02/07-02/08-24
  clusters/hosted_control_planes/hosted_intro.adoc
  clusters/release_notes/known_issues.adoc
  release_notes/known_issues_observability.adoc
Labels: lgtm

#6115 added subscription status
  applications/subscription_report.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#6131 ACM-9804 Remove old known issues for search
  release_notes/known_issues_console.adoc
Labels: lgtm

#6132 Swope cherrypick
  install/install_connected.adoc
Labels: needs-rebase

#6111 https://issues.redhat.com/browse/ACM-7924 Updates for concurrency gov framework
  governance/policy_ctrl_adv_config.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#6137 Swope cust
  clusters/install_upgrade/install_connected.adoc
  install/install_connected.adoc
Labels: needs-rebase

#6113 IBM Z documentation updates for HCP
  clusters/hosted_control_planes/add_agents_ibmz.adoc
  clusters/hosted_control_planes/ibmz_intro.adoc
  clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
Labels: lgtm

#6099 ACM#9564: Update examples for configuting metallb
  clusters/hosted_control_planes/config_metallb_bm.adoc
Labels: lgtm

#6121 https://issues.redhat.com/browse/ACM-8532 Remove BMH docs
  clusters/cluster_lifecycle/cim_auto_add_host.adoc
Labels: lgtm

#6126 https://issues.redhat.com/browse/ACM-9739 Errata MCE 2.3.5
  clusters/release_notes/errata.adoc
Labels: lgtm

#6138 2.7 refresh 02/14-02/15
  clusters/install_upgrade/install_connected.adoc
  install/install_connected.adoc
Labels: lgtm

#6136 2.8 refresh 02/14-02/15
  clusters/install_upgrade/install_connected.adoc
  clusters/release_notes/errata.adoc
  install/install_connected.adoc
  release_notes/errata.adoc
Labels: lgtm

#6140 2.9 refresh 02/15
  clusters/install_upgrade/install_connected.adoc
  install/install_connected.adoc
Labels: lgtm

#6104 IBM Power documentation updates for HCP
  clusters/hosted_control_planes/ibmpower_intro.adoc
  clusters/hosted_control_planes/scale_nodepool_hosted_ibmpower.adoc
  clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
Labels: lgtm

#6098 ACM#9255: Add description for Cluster OS image
  clusters/credentials/credential_vm.adoc
Labels: lgtm

#6154 ACM#9987: Adding relase notes entries for hosted control planes
  clusters/release_notes/whats_new.adoc
Labels: lgtm

#6147 https://issues.redhat.com/browse/ACM-8848
  clusters/cluster_lifecycle/remove_cl_clusterset.adoc
Labels: lgtm

#6124 https://issues.redhat.com/browse/ACM-9833 Update known issue
  clusters/release_notes/known_issues.adoc
Labels: lgtm

#6167 https://issues.redhat.com/browse/ACM-9187 Add descriptions doc
  governance/policy_generator.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#6168 https://issues.redhat.com/browse/ACM-9188 Add policyLabels doc
  governance/policy_generator.adoc
Labels: lgtm

#6170 https://issues.redhat.com/browse/ACM-9858 Add IBM Power support docs
  networking/submariner/deploy_subm_console.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#6156 added content on dashboard alerts
  observability/design_grafana.adoc
Labels: lgtm

#6158 (2.9) Added Component Table for MultiClusterEngine
  clusters/install_upgrade/adv_config_install.adoc
Labels: lgtm

#6169 https://issues.redhat.com/browse/ACM-10011 YAML bug fix
  clusters/cluster_lifecycle/release_images_specify.adoc
Labels: lgtm

#6127 added content on policy
  business_continuity/backup_restore/backup_validate.adoc
  release_notes/whats_new.adoc
Labels: lgtm, do-not-merge/hold
