Repository stolostron/rhacm-docs, pull requests merged in 2024-05, with the labels that each got.

#6371 Fix the operator policy documentation
  governance/install_operator.adoc
  governance/policy_operator.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#6381 Clean unused files; Fix GRC links
  governance/grc_intro.adoc
  governance/security_overview.adoc
  governance/third_party_policy_intro.adoc
  modules/modules
Labels: lgtm

#6402 fixed typo
  clusters/cluster_lifecycle/create_clusterset.adoc
  clusters/cluster_lifecycle/placement_filter.adoc
Labels: lgtm

#6392 [ACM-2.11] ACM#10464: Extracting OpenShift release image digest
  clusters/hosted_control_planes/create_cluster_bm.adoc
  clusters/hosted_control_planes/disconnected_intro.adoc
Labels: lgtm

#6377 https://issues.redhat.com/browse/ACM-10994 Add control plane node topic
  clusters/cluster_lifecycle/scale_managed_intro.adoc
  clusters/cluster_lifecycle/scale_node_ctrl_plane.adoc
  clusters/main.adoc
Labels: lgtm

#6412 removed unneeded cluterview
  business_continuity/backup_restore/backup_arch.adoc
Labels: lgtm

#6361 https://issues.redhat.com/browse/ACM-10752
  _pages/advisory_review.md
Labels: lgtm

#6414 Refresh 05/08-05/09
  clusters/cluster_lifecycle/create_clusterset.adoc
  clusters/cluster_lifecycle/placement_filter.adoc
  clusters/cluster_lifecycle/scale_managed_intro.adoc
  clusters/cluster_lifecycle/scale_node_ctrl_plane.adoc
  clusters/hosted_control_planes/create_cluster_bm.adoc
  clusters/hosted_control_planes/deploy_cluster_aws.adoc
  clusters/hosted_control_planes/destroy_cluster_aws.adoc
  clusters/hosted_control_planes/destroy_cluster_kubevirt.adoc
  clusters/hosted_control_planes/destroy_hosted_bm.adoc
  clusters/hosted_control_planes/destroy_non_bm.adoc
  clusters/hosted_control_planes/disable_auto_import.adoc
  clusters/hosted_control_planes/disable_hosted.adoc
  clusters/hosted_control_planes/disconnected_dual_stack_intro.adoc
  clusters/hosted_control_planes/disconnected_intro.adoc
  clusters/hosted_control_planes/disconnected_ipv4_intro.adoc
  clusters/hosted_control_planes/disconnected_ipv6_intro.adoc
  clusters/hosted_control_planes/distribute_cluster_workloads.adoc
  clusters/hosted_control_planes/dual_stack_dns.adoc
  clusters/hosted_control_planes/dual_stack_finish_deployment.adoc
  clusters/main.adoc
  governance/grc_intro.adoc
  governance/security_overview.adoc
  governance/third_party_policy_intro.adoc
  release_notes/known_issues_application.adoc
Labels: lgtm

#6408 [ACM-2.10] ACM#11454: Add the topology.kubernetes.io/zone label to bare metal hosts
  clusters/hosted_control_planes/bm_intro.adoc
Labels: lgtm

#6407 [ACM-2.11] ACM#11454: Add the topology.kubernetes.io/zone label to bare metal hosts
  clusters/hosted_control_planes/bm_intro.adoc
Labels: lgtm

#6396 https://issues.redhat.com/browse/ACM-11433 Remove unused html files
  about/master.html
  add-ons/master.html
  apis/master.html
  applications/master.html
  console/master.html
  governance/master.html
  health_metrics/master.html
  install/master.html
  networking/master.html
  release_notes/master.html
  troubleshooting/master.html
Labels: lgtm

#6390 https://issues.redhat.com/browse/ACM-11181 Partial matching search
  observability/manage_search.adoc
  observability/search_intro.adoc
  release_notes/whats_new.adoc
Labels: do-not-merge/hold

#6417 Add Sprig functions to GRC template doc
  governance/template_functions.adoc
Labels: lgtm

#6432 https://issues.redhat.com/browse/ACM-11429 Z-stream errata for MCE 2.5.3
  clusters/release_notes/errata.adoc
Labels: lgtm

#6378 Document template support in OperatorPolicy
  governance/policy_operator.adoc
  governance/template_support_intro.adoc
Labels: lgtm

#6433 https://issues.redhat.com/browse/ACM-11428 z-stream ACM 2.10.3
  release_notes/errata.adoc
Labels: lgtm

#6445 https://issues.redhat.com/browse/ACM-11399 adding what's new entry
  release_notes/whats_new.adoc
Labels: lgtm

#6431 added new troubleshooting topic for search databases
  troubleshooting/main.adoc
  troubleshooting/trouble_search_database.adoc
Labels: lgtm

#6449 https://issues.redhat.com/browse/ACM-11340 global KlusterletConfig docs
  clusters/cluster_lifecycle/adv_config_cluster.adoc
  clusters/release_notes/whats_new.adoc
Labels: lgtm

#6452 remove duplicate content
  global_hub/global_hub_access_data.adoc
Labels: lgtm

#6455 2.10 refresh
  clusters/hosted_control_planes/config_metallb_bm.adoc
  clusters/hosted_control_planes/handle_ingress_bm.adoc
  clusters/hosted_control_planes/hosted_sizing_guidance.adoc
  clusters/hosted_control_planes/ingress_non_bm.adoc
  global_hub/global_hub_access_data.adoc
Labels: lgtm

#6457 https://issues.redhat.com/browse/ACM-11353 adding info to policy table-using attribute for proper OLM name
  governance/policy_operator.adoc
Labels: lgtm

#6465 Swope cherry pick3
  install/upgrade_hub.adoc
Labels: needs-rebase

#6451 ACM#11259: Mapping the infrastructure KubeVirt CSI volume snapshot class
  clusters/hosted_control_planes/config_storage_kubevirt.adoc
Labels: lgtm

#6369 https://issues.redhat.com/browse/ACM-10127
  observability/customize_observability.adoc
Labels: lgtm

#6473 Swope fix3 cherry pick
  applications/configuring_git_channel.adoc
Labels: needs-rebase

#6477 2.9 refresh
  applications/configuring_git_channel.adoc
  install/upgrade_hub.adoc
Labels: lgtm

#6418 added workaround section for troubleshooting
  add-ons/configure_nodeselector_tolerations_addons.adoc
  troubleshooting/trouble_cluster_ignoring_addon.adoc
  troubleshooting/troubleshooting_intro.adoc
Labels: lgtm

#6481 2.9 Refresh, second attempt after accidentally refreshing
  clusters/release_notes/errata.adoc
  observability/customize_observability.adoc
Labels: lgtm

#6482 https://issues.redhat.com/browse/ACM-11786 hide content
  clusters/release_notes/errata.adoc
Labels: lgtm

#6483 2.9 re-refresh
  clusters/cluster_lifecycle/cim_enable.adoc
  clusters/release_notes/errata.adoc
Labels: lgtm
