Repository stolostron/rhacm-docs, pull requests merged in 2024-07, with the labels that each got.

#6582 https://issues.redhat.com/browse/ACM-12135 Clarify restore
  business_continuity/backup_restore/backup_restore.adoc
Labels: lgtm

#6584 ACM-12171: Add whats new and deprecated info
  clusters/release_notes/deprecate_remove.adoc
  clusters/release_notes/whats_new.adoc
Labels: lgtm

#6575 added sub step for passive hub cluster
  business_continuity/backup_restore/backup_install.adoc
Labels: lgtm

#6580 https://issues.redhat.com/browse/ACM-11764
  release_notes/known_issues_observability.adoc
Labels: lgtm

#6594 Update the global hub database for troubleshooting
  troubleshooting/trouble_global_hub_access_postgres.adoc
Labels: lgtm

#6613 https://issues.redhat.com/browse/ACM-12363 simple release note, no need for immediate refresh
  clusters/release_notes/errata.adoc
Labels: lgtm

#6615 Fix build error
  clusters/release_notes/whats_new.adoc
Labels: lgtm

#6605 removed backtick
  observability/customize_observability.adoc
Labels: lgtm

#6602 removed antiquated known issue
  release_notes/known_issues_application.adoc
Labels: lgtm

#6619 Update errata.adoc same clean up
  clusters/release_notes/errata.adoc
Labels: lgtm

#6617 Update whats_new.adoc link fix
  clusters/release_notes/whats_new.adoc
Labels: lgtm

#6487 WIP: ACM-11775 (needs issue links-peer edits)
  clusters/hosted_control_planes/add_agents_ibmz.adoc
  clusters/hosted_control_planes/destroying-hosted-clusted-x86bm-ibmz.adoc
  clusters/hosted_control_planes/ibmz_intro.adoc
  clusters/hosted_control_planes/scale_nodepool_hosted_ibmpower.adoc
  clusters/hosted_control_planes/scale_nodepool_hosted_ibmz.adoc
Labels: lgtm, do-not-merge/work-in-progress

#6623 [ACM-11775]: Cleaning up formatting in IBM Z files
  clusters/hosted_control_planes/add_agents_ibmz.adoc
  clusters/hosted_control_planes/destroy_hosted_cluster_x86bm_ibmz.adoc
  clusters/main.adoc
Labels: lgtm

#6625 Fixing release note book for 2.11
  release_notes/known_issues_observability.adoc
Labels: lgtm

#6627 fixed link
  business_continuity/backup_restore/backup_schedule.adoc
Labels: lgtm

#6576 [ACM-11392: Clarify storage support for HCP OCP Virtualization Provider
  clusters/hosted_control_planes/config_storage_kubevirt.adoc
Labels: lgtm

#6611 https://issues.redhat.com/browse/ACM-11844
  clusters/cluster_lifecycle/cim_enable.adoc
Labels: lgtm

#6607 [MGMT-17103]: Known issue for HCP on IBM Z
  clusters/release_notes/known_issues.adoc
Labels: lgtm

#6642 No Jira: Fixing error
  clusters/release_notes/known_issues.adoc
Labels: lgtm

#6644 https://issues.redhat.com/browse/ACM-12357 Add prereq Subm
  networking/submariner/subm_configure.adoc
Labels: lgtm

#6637 https://issues.redhat.com/browse/ACM-12115 tech debt
  clusters/cluster_lifecycle/clusterclaims.adoc
  clusters/cluster_lifecycle/config_manifest_create.adoc
  clusters/cluster_lifecycle/custom_clusterclaims.adoc
  clusters/cluster_lifecycle/release_images_specify.adoc
  clusters/cluster_lifecycle/upgrade_cluster.adoc
  clusters/cluster_lifecycle/upgrade_cluster_disconnected.adoc
  clusters/main.adoc
Labels: lgtm

#6648 fixed typo
  add-ons/cluster_wide_proxy.adoc
Labels: lgtm

#6649 fixed typo for 2.10
  add-ons/cluster_wide_proxy.adoc
Labels: lgtm

#6653 Refresh PR for ACM 2.10.4 and MCE 2.5.5
  add-ons/cluster_wide_proxy.adoc
  business_continuity/backup_restore/backup_arch.adoc
  business_continuity/backup_restore/backup_install.adoc
  business_continuity/backup_restore/backup_restore.adoc
  business_continuity/backup_restore/backup_schedule.adoc
  clusters/cluster_lifecycle/cim_enable.adoc
  clusters/release_notes/errata.adoc
  networking/submariner/install_subctl.adoc
  networking/submariner/subm_configure.adoc
  observability/customize_observability.adoc
  release_notes/errata.adoc
  release_notes/known_issues_continuity.adoc
Labels: lgtm

#6643 Add a description for --api-server-address for Agent
  clusters/hosted_control_planes/create_cluster_bm.adoc
  clusters/hosted_control_planes/create_cluster_non_bm.adoc
Labels: lgtm

#6659 Updates for cluster book to fix pantheon
  clusters/discovery/discovery_intro.adoc
  clusters/discovery/enable_discovery.adoc
Labels: lgtm

#6660 https://issues.redhat.com/browse/ACM-9830--ocp versions the bottom of…
  clusters/cluster_lifecycle/cim_enable.adoc
  clusters/cluster_lifecycle/cim_intro.adoc
  clusters/cluster_lifecycle/cluster_lifecycle_arch.adoc
  clusters/cluster_lifecycle/create_aws_govcloud.adoc
  clusters/cluster_lifecycle/create_azure.adoc
  clusters/cluster_lifecycle/create_cluster_on_prem.adoc
  clusters/cluster_lifecycle/create_google.adoc
  clusters/cluster_lifecycle/create_ocp_aws.adoc
  clusters/cluster_lifecycle/create_openstack.adoc
  clusters/cluster_lifecycle/create_vm.adoc
  clusters/cluster_lifecycle/import_cli.adoc
  clusters/cluster_lifecycle/release_image_disconn.adoc
  clusters/cluster_lifecycle/single_node_ocp.adoc
  clusters/cluster_lifecycle/upgrade_cluster_disconnected.adoc
  clusters/credentials/credential_on_prem.adoc
  clusters/credentials/credential_openstack.adoc
  clusters/credentials/credential_vm.adoc
  clusters/hosted_control_planes/dual_stack_tls_certs.adoc
  clusters/hosted_control_planes/ipv4_tls_certs.adoc
  clusters/hosted_control_planes/ipv6_tls_certs.adoc
  clusters/hosted_control_planes/managing_hosted_bm_ibmz.adoc
  clusters/install_upgrade/install_connected.adoc
  clusters/install_upgrade/install_disconnected.adoc
  clusters/install_upgrade/uninstall.adoc
  clusters/release_notes/known_issues.adoc
  clusters/support_troubleshooting/must_gather_mce.adoc
  gitops/deploy_gitops.adoc
  gitops/gitops_policy_generator.adoc
  global_hub/global_hub_install_connected.adoc
  global_hub/global_hub_install_disconnected.adoc
  governance/certificates.adoc
  governance/compliance_operator_policy.adoc
  governance/create_gatekeeper.adoc
  governance/e8_scan_policy.adoc
  governance/manage_operator.adoc
  governance/ocp_cis_policy.adoc
  governance/policy_operator.adoc
  governance/supported_policies.adoc
  install/cluster_size.adoc
  install/install_connected.adoc
  install/install_disconnected.adoc
  install/uninstall.adoc
  install/upgrade_cluster_disconnected_policies.adoc
  install/upgrade_hub.adoc
  networking/network_config_hub.adoc
  observability/customize_observability.adoc
  observability/observability_enable.adoc
  observability/observe_environments.adoc
  release_notes/fips_readiness.adoc
Labels: lgtm

#6651 ACM-12682: update hcp doc
  clusters/hosted_control_planes/create_hosted_aws.adoc
  clusters/hosted_control_planes/create_role_sts_aws.adoc
Labels: lgtm

#6663 https://issues.redhat.com/browse/ACM-9830
  clusters/cluster_lifecycle/cim_enable.adoc
Labels: lgtm

#6652 https://issues.redhat.com/browse/ACM-12605
  observability/customize_observability.adoc
Labels: lgtm

#6662 careful change to versions
  clusters/cluster_lifecycle/cluster_pool_create.adoc
  clusters/cluster_lifecycle/clusterclaims.adoc
  clusters/cluster_lifecycle/create_cluster_on_prem.adoc
  clusters/cluster_lifecycle/create_single_node_ocp_clusterpool.adoc
  clusters/cluster_lifecycle/create_vm.adoc
  clusters/cluster_lifecycle/import_agent.adoc
  clusters/cluster_lifecycle/import_cli.adoc
  clusters/cluster_lifecycle/import_gui.adoc
  clusters/cluster_lifecycle/single_node_ocp.adoc
  clusters/cluster_lifecycle/upgrade_cluster_disconnected.adoc
  clusters/credentials/credential_openstack.adoc
  clusters/credentials/credential_vm.adoc
  networking/network_config_hub.adoc
  networking/network_config_managed.adoc
Labels: lgtm

#6669 Swope links4
  apis/discoveryconfig.json.adoc
  clusters/cluster_lifecycle/cim_enable.adoc
  clusters/cluster_lifecycle/clusterclaims.adoc
  clusters/cluster_lifecycle/create_cluster_on_prem.adoc
  clusters/cluster_lifecycle/create_vm.adoc
  clusters/cluster_lifecycle/import_cli.adoc
  clusters/cluster_lifecycle/upgrade_cluster_disconnected.adoc
  clusters/install_upgrade/install_disconnected.adoc
  install/install_connected.adoc
  install/upgrade_cluster_disconnected_policies.adoc
  networking/submariner/subm_configure.adoc
  observability/observability_enable.adoc
Labels: needs-rebase

#6667 ACM-9830--carefully changing, eliminating, or reducing long ways of saying simple things
  .github/workflows/linting.yml
  clusters/cluster_lifecycle/cluster_pool_create.adoc
  clusters/cluster_lifecycle/create_single_node_ocp_clusterpool.adoc
  clusters/cluster_lifecycle/import_gui.adoc
  observability/customize_observability.adoc
Labels: lgtm

#6655 added known issue for grafana
  release_notes/known_issues_global.adoc
Labels: lgtm

#6647 improved and added steps for restore hub
  business_continuity/backup_restore/backup_install.adoc
Labels: lgtm

#6521 [ACM-11953]: Remove/replace references to hypershift CLI
  clusters/hosted_control_planes/deploy_aws_private_clusters.adoc
  clusters/hosted_control_planes/enable_ext_dns_aws.adoc
  clusters/hosted_control_planes/install_hcp_cli.adoc
  clusters/hosted_control_planes/manage_aws_infra_iam.adoc
Labels: lgtm

#6650 https://issues.redhat.com/browse/ACM-8481
  observability/use_observability.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#6679 api versions
  apis/addondeploymentconfig.json.adoc
  apis/application.json.adoc
  apis/channels.json.adoc
  apis/cluster.json.adoc
  apis/clustermanagementaddon.json.adoc
  apis/clusterset.json.adoc
  apis/clustersetbinding.json.adoc
  apis/clusterview.json.adoc
  apis/compliancehistory.json.adoc
  apis/discoveredcluster.json.adoc
  apis/discoveryconfig.json.adoc
  apis/helmreleases.json.adoc
  apis/klusterletconfig.json.adoc
  apis/managedclusteraddon.json.adoc
  apis/managedclusterset.json.adoc
  apis/multicluster_hub.json.adoc
  apis/observability.json.adoc
  apis/placement.json.adoc
  apis/placementdecision.json.adoc
  apis/placementrules.json.adoc
  apis/policy.json.adoc
  apis/subscriptions.json.adoc
  clusters/cluster_lifecycle/single_node_ocp.adoc
  clusters/discovery/discovery_config_cli.adoc
  clusters/install_upgrade/install_disconnected.adoc
  governance/ansible_grc.adoc
  governance/opp_policyset.adoc
  governance/psp_policy.adoc
  install/upgrade_cluster_disconnected_policies.adoc
Labels: lgtm

#6677 Fixing the cluster book for 2.11
  clusters/hosted_control_planes/deploy_aws_private_clusters.adoc
Labels: lgtm

#6684 https://issues.redhat.com/browse/ACM-12721 Standardize naming
  clusters/about/mce_networking.adoc
Labels: lgtm

#6687 https://issues.redhat.com/browse/ACM-12486 MCE whats new quick review
  clusters/release_notes/whats_new.adoc
Labels: lgtm

#6693 making another attempt to fix Clusters book
  clusters/acm_integration/acm_discover_hosted.adoc
  clusters/cluster_lifecycle/release_images_specify.adoc
Labels: lgtm

#6695 Remove potential problem with header
  clusters/acm_integration/acm_integrate_import_hcp.adoc
Labels: lgtm

#6694 [ACM-12774]: Fixing command in HCP docs
  clusters/hosted_control_planes/scale_node_pool_kubevirt.adoc
Labels: lgtm

#6699 Small fixes after publishing 2.11
  access_control/access_intro.adoc
  apis/multicluster_hub.json.adoc
  applications/ansible_config.adoc
  applications/ansible_intro.adoc
  business_continuity/backup_restore/backup_install.adoc
  clusters/cluster_lifecycle/single_node_ocp.adoc
  clusters/discovery/enable_discovery.adoc
  global_hub/global_hub_install_disconnected.adoc
  global_hub/global_search.adoc
  governance/scc_policy.adoc
  install/upgrade_cluster_disconnected_policies.adoc
  modules/common-attributes.adoc
  release_notes/known_issues_application.adoc
  release_notes/known_issues_global.adoc
Labels: lgtm

#6700 https://issues.redhat.com/browse/ACM-9830--rhel versions for mustgather
  clusters/support_troubleshooting/must_gather_mce.adoc
  troubleshooting/must_gather.adoc
Labels: lgtm

#6703 https://issues.redhat.com/browse/ACM-https://issues.redhat.com/browse…
  install/install_connected.adoc
  install/install_disconnected.adoc
  install/upgrade_cluster_disconnected_policies.adoc
Labels: lgtm

#6705 https://issues.redhat.com/browse/ACM-11974--all over the place with v…
  install/cluster_size.adoc
  install/install_connected.adoc
  install/install_disconnected.adoc
  install/uninstall.adoc
  install/upgrade_cluster_disconnected_policies.adoc
Labels: lgtm

#6704 https://issues.redhat.com/browse/ACM-https://issues.redhat.com/browse…
  business_continuity/backup_restore/backup_install.adoc
  install/cluster_size.adoc
  install/upgrade_cluster_disconnected_policies.adoc
Labels: lgtm

#6681 added context to known issue
  clusters/release_notes/known_issues.adoc
Labels: lgtm

#6708 Refresh for 2.11 FINALLY!
  access_control/access_intro.adoc
  apis/multicluster_hub.json.adoc
  applications/ansible_config.adoc
  applications/ansible_intro.adoc
  business_continuity/backup_restore/backup_install.adoc
  clusters/api/api_intro.adoc
  clusters/cluster_lifecycle/adv_config_cluster.adoc
  clusters/cluster_lifecycle/placement_overview.adoc
  clusters/cluster_lifecycle/single_node_ocp.adoc
  clusters/cluster_mce_overview.adoc
  clusters/discovery/enable_discovery.adoc
  clusters/hosted_control_planes/access_hosted_cluster.adoc
  clusters/hosted_control_planes/aws_intro.adoc
  clusters/hosted_control_planes/bm_intro.adoc
  clusters/hosted_control_planes/deploy_aws_private_clusters.adoc
  clusters/hosted_control_planes/disable_hosted.adoc
  clusters/hosted_control_planes/distribute_cluster_workloads.adoc
  clusters/hosted_control_planes/enable_hcp_on_arm.adoc
  clusters/hosted_control_planes/hosted_intro.adoc
  clusters/hosted_control_planes/ibmz_intro.adoc
  clusters/hosted_control_planes/kubevirt_intro.adoc
  clusters/hosted_control_planes/scale_node_pool_kubevirt.adoc
  clusters/release_notes/known_issues.adoc
  clusters/release_notes/whats_new.adoc
  clusters/support_troubleshooting/must_gather_mce.adoc
  clusters/support_troubleshooting/troubleshooting_mce_intro.adoc
  global_hub/global_hub_install_disconnected.adoc
  global_hub/global_search.adoc
  governance/scc_policy.adoc
  install/upgrade_cluster_disconnected_policies.adoc
  modules/common-attributes.adoc
  observability/observability_alerts.adoc
  release_notes/known_issues_application.adoc
  release_notes/known_issues_global.adoc
  release_notes/known_issues_governance.adoc
  troubleshooting/must_gather.adoc
Labels: lgtm

#6710 ACM-12912: fix json code syntax
  clusters/hosted_control_planes/create_role_sts_aws.adoc
Labels: lgtm

#6711 When we don't have an entry, we have to remove the section
  release_notes/whats_new.adoc
Labels: lgtm

#6712 Fixing broken link in what's new
  clusters/release_notes/whats_new.adoc
Labels: lgtm

#6709 https://issues.redhat.com/browse/ACM-12898
  about/architecture.adoc
  about/welcome.adoc
  clusters/about/mce_intro.adoc
  clusters/install_upgrade/install_intro.adoc
  governance/create_gatekeeper.adoc
  governance/gatekeeper_operator_intro.adoc
  install/install_overview.adoc
  modules/common-attributes.adoc
  networking/submariner/subm_intro.adoc
  release_notes/known_issues_network.adoc
Labels: lgtm

#6713 https://issues.redhat.com/browse/ACM-12815--release note
  clusters/release_notes/errata.adoc
  release_notes/errata.adoc
Labels: lgtm

#6715 added known issue for proxy addon
  release_notes/known_issues_continuity.adoc
Labels: lgtm

#6718 2.9 Refresh
  business_continuity/backup_restore/backup_install.adoc
  business_continuity/backup_restore/backup_restore.adoc
  business_continuity/backup_restore/backup_schedule.adoc
  clusters/cluster_lifecycle/scale_managed_intro.adoc
  clusters/cluster_lifecycle/scale_node_ctrl_plane.adoc
  clusters/main.adoc
  install/cluster_size.adoc
  install/upgrade_cluster_disconnected_policies.adoc
  observability/customize_observability.adoc
  release_notes/known_issues_continuity.adoc
  troubleshooting/trouble_already_exists.adoc
Labels: lgtm

#6717 2.10 Refresh
  business_continuity/backup_restore/backup_install.adoc
  business_continuity/backup_restore/backup_schedule.adoc
  clusters/about/mce_networking.adoc
  clusters/hosted_control_planes/scale_node_pool_kubevirt.adoc
  clusters/release_notes/known_issues.adoc
  governance/create_gatekeeper.adoc
  governance/gatekeeper_operator_intro.adoc
  install/install_connected.adoc
  install/install_disconnected.adoc
  install/upgrade_cluster_disconnected_policies.adoc
  observability/customize_observability.adoc
  observability/observability_alerts.adoc
  release_notes/known_issues_continuity.adoc
  release_notes/known_issues_global.adoc
  troubleshooting/trouble_already_exists.adoc
Labels: lgtm

#6726 refresh 2.11
  about/architecture.adoc
  about/welcome.adoc
  clusters/about/mce_intro.adoc
  clusters/acm_integration/acm_integrate_intro.adoc
  clusters/hosted_control_planes/create_role_sts_aws.adoc
  clusters/install_upgrade/install_intro.adoc
  clusters/release_notes/whats_new.adoc
  governance/create_gatekeeper.adoc
  governance/gatekeeper_operator_intro.adoc
  install/install_overview.adoc
  networking/submariner/subm_intro.adoc
  observability/customize_observability.adoc
  release_notes/known_issues_network.adoc
  release_notes/whats_new.adoc
Labels: lgtm

#6727 ACM-12912: add one permission in JSON
  clusters/hosted_control_planes/create_role_sts_aws.adoc
Labels: lgtm

#6728 [HOSTEDCP-1798]: Update docs about multi-arch flag for HCP
  clusters/hosted_control_planes/enable_hcp_on_arm.adoc
Labels: lgtm

#6680 https://issues.redhat.com/browse/ACM-11809 Unbind non bm troubleshoot
  clusters/main.adoc
  clusters/support_troubleshooting/trouble_unbind_non_bm.adoc
Labels: lgtm

#6697 https://issues.redhat.com/browse/ACM-12788
  release_notes/known_issues_observability.adoc
Labels: lgtm

#6732 https://issues.redhat.com/browse/ACM-12776--this adds some customer b…
  release_notes/errata.adoc
Labels: lgtm

#6734 2.8 refresh
  business_continuity/backup_restore/backup_arch.adoc
  clusters/cluster_lifecycle/cim_enable.adoc
  clusters/cluster_lifecycle/scale_managed_intro.adoc
  clusters/cluster_lifecycle/scale_node_ctrl_plane.adoc
  clusters/main.adoc
  clusters/release_notes/errata.adoc
  clusters/release_notes/known_issues.adoc
  governance/main.adoc
  governance/supported_policies.adoc
  install/cluster_size.adoc
  install/install_connected.adoc
  install/install_disconnected.adoc
  install/uninstall.adoc
  install/upgrade_cluster_disconnected_policies.adoc
  observability/customize_observability.adoc
  release_notes/errata.adoc
  release_notes/known_issues_continuity.adoc
Labels: lgtm
