Repository stolostron/rhacm-docs, pull requests merged in 2025-04, with the labels that each got.

#7666 https://issues.redhat.com/browse/ACM-19526
  release_notes/errata.adoc
Labels: lgtm

#7673 Merge when ready: notes for peer review with writer/meeting
  governance/cert_policy_ctrl.adoc
  secure_cluster/cert_intro.adoc
  secure_cluster/cert_manage.adoc
  secure_cluster/certificates.adoc
  secure_cluster/main.adoc
  secure_cluster/securing_cluster_intro.adoc
Labels: lgtm

#7688 https://issues.redhat.com/browse/ACM-16008 Add default metrics to doc
  observability/obs_config.adoc
Labels: lgtm

#7690 2.9 stage
  business_continuity/backup_restore/backup_hub_config.adoc
  clusters/cluster_lifecycle/cim_create_cli.adoc
  clusters/cluster_lifecycle/scale_node_ocp.adoc
  release_notes/errata.adoc
Labels: lgtm

#7693 2.11 stage
  business_continuity/backup_restore/backup_install.adoc
  clusters/cluster_lifecycle/cim_create_cli.adoc
  clusters/cluster_lifecycle/cluster_proxy_addon.adoc
  clusters/cluster_lifecycle/scale_machinepool.adoc
  clusters/cluster_lifecycle/scale_node_ocp.adoc
  clusters/install_upgrade/config_infra_nodes_mce.adoc
  install/upgrade_hub.adoc
  observability/customize_observability.adoc
  observability/obs_config.adoc
Labels: lgtm

#7694 2.10 stage
  business_continuity/backup_restore/backup_hub_config.adoc
  business_continuity/backup_restore/backup_restore.adoc
  clusters/cluster_lifecycle/cim_create_cli.adoc
  clusters/cluster_lifecycle/scale_node_ocp.adoc
  observability/customize_observability.adoc
Labels: lgtm

#7686 https://issues.redhat.com/browse/ACM-19151--upgrade, Obs.
  release_notes/known_issues_install.adoc
Labels: lgtm

#7691 2.12 refresh Apr 4 2025
  clusters/assisted_installer/ai_create_cli.adoc
  clusters/cluster_lifecycle/scale_node_ocp.adoc
  clusters/credentials/credential_vm.adoc
  observability/customize_observability.adoc
  observability/obs_config.adoc
Labels: lgtm

#7696 2.13 refresh
  about/docinfo.xml
  add-ons/docinfo.xml
  applications/docinfo.xml
  business_continuity/docinfo.xml
  clusters/assisted_installer/ai_create_cli.adoc
  clusters/cluster_lifecycle/scale_node_ocp.adoc
  clusters/docinfo.xml
  console/docinfo.xml
  edge_manager/docinfo.xml
  gitops/docinfo.xml
  global_hub/docinfo.xml
  governance/cert_policy_ctrl.adoc
  governance/docinfo.xml
  health_metrics/docinfo.xml
  install/docinfo.xml
  mce_acm_integration/docinfo.xml
  mce_acm_integration/siteconfig/siteconfig_install_clusters.adoc
  observability/customize_observability.adoc
  observability/obs_config.adoc
  release_notes/docinfo.xml
  release_notes/known_issues_install.adoc
  secure_cluster/cert_intro.adoc
  secure_cluster/cert_manage.adoc
  secure_cluster/certificates.adoc
  secure_cluster/docinfo.xml
  secure_cluster/main.adoc
  secure_cluster/securing_cluster_intro.adoc
  troubleshooting/must_gather_acm.adoc
Labels: lgtm

#7685 https://issues.redhat.com/browse/ACM-18744
  governance/cert_policy_ctrl.adoc
  governance/compliance_operator_policy.adoc
  governance/config_policy_ctrl.adoc
  governance/create_config_pol.adoc
  governance/e8_scan_policy.adoc
  governance/etcd_encryption_policy.adoc
  governance/grc_arch.adoc
  governance/image_vuln_policy.adoc
  governance/manage_policies.adoc
  governance/memory_policy.adoc
  governance/namespace_policy.adoc
  governance/ocp_cis_policy.adoc
  governance/opp_policyset.adoc
  governance/opp_policyset_install.adoc
  governance/pod_policy.adoc
  governance/policy_set_ctrl.adoc
  governance/psp_policy.adoc
  governance/role_policy.adoc
  governance/rolebinding_policy.adoc
  governance/scc_policy.adoc
  release_notes/known_issues_governance.adoc
Labels: lgtm

#7698 https://issues.redhat.com/browse/ACM-18742
  gitops/deploy_gitops.adoc
  gitops/gitops_registering.adoc
Labels: lgtm

#7700 Swope 2.12 descriptions
  about/docinfo.xml
  access_control/docinfo.xml
  add-ons/docinfo.xml
  apis/docinfo.xml
  applications/docinfo.xml
  business_continuity/docinfo.xml
  clusters/docinfo.xml
  console/docinfo.xml
  gitops/docinfo.xml
  global_hub/docinfo.xml
  governance/docinfo.xml
  health_metrics/docinfo.xml
  install/docinfo.xml
  networking/docinfo.xml
  observability/docinfo.xml
  release_notes/docinfo.xml
  troubleshooting/docinfo.xml
Labels: needs-rebase

#7709 https://issues.redhat.com/browse/ACM-19431
  release_notes/acm_errata.adoc
Labels: lgtm

#7717 The last 2.10 refresh ever (probably) Apr 10 2025
  governance/cert_manage.adoc
  observability/use_observability.adoc
Labels: lgtm

#7716 https://issues.redhat.com/browse/ACM-19816--Fix MCH namespace in Enabling SiteConfig operator docs
  mce_acm_integration/siteconfig/siteconfig_enable.adoc
Labels: lgtm

#7718 https://issues.redhat.com/browse/ACM-19816--Fix MCH namespace in Enabling SiteConfig operator docs
  mce_acm_integration/siteconfig/siteconfig_enable.adoc
Labels: lgtm

#7721 https://issues.redhat.com/browse/ACM-19151#
  release_notes/known_issues_install.adoc
Labels: lgtm

#7729 2.12 refresh
  about/docinfo.xml
  access_control/docinfo.xml
  add-ons/docinfo.xml
  apis/docinfo.xml
  applications/docinfo.xml
  business_continuity/docinfo.xml
  clusters/docinfo.xml
  console/docinfo.xml
  gitops/docinfo.xml
  global_hub/docinfo.xml
  governance/cert_manage.adoc
  governance/docinfo.xml
  health_metrics/docinfo.xml
  install/config_infra_nodes_acm.adoc
  install/docinfo.xml
  mce_acm_integration/siteconfig/siteconfig_enable.adoc
  networking/docinfo.xml
  observability/customize_observability.adoc
  observability/docinfo.xml
  observability/use_observability.adoc
  release_notes/docinfo.xml
  release_notes/known_issues_install.adoc
  troubleshooting/docinfo.xml
Labels: lgtm

#7731 2.10 refresh
  governance/cert_manage.adoc
Labels: lgtm

#7734 https://issues.redhat.com/browse/ACM-19663 Subm version update
  networking/submariner/deploy_subm_console.adoc
  networking/submariner/subm_disconnected.adoc
  networking/submariner/uninstall_subm.adoc
Labels: lgtm

#7543 Add steps for setting up local build on Linux in Refresh builds
  _pages/refresh_builds.md
Labels: lgtm

#7728 https://issues.redhat.com/browse/ACM-19431
  release_notes/acm_errata.adoc
Labels: lgtm

#7738 https://issues.redhat.com/browse/ACM-19434
  clusters/release_notes/mce_errata.adoc
Labels: lgtm

#7737 ACM 2.12.3 Errata
  release_notes/acm_errata.adoc
Labels: lgtm, do-not-merge/hold

#7740 Cwall cluster role cleanup
  install/cleanup_reinstall.adoc
Labels: lgtm

#7720 https://issues.redhat.com/browse/ACM-19151--2.13.2 additional content needed now
  release_notes/known_issues_install.adoc
Labels: lgtm

#7743 Refresh 2.13
  .github/workflows/linting.yml
  business_continuity/backup_restore/backup_restore.adoc
  clusters/release_notes/mce_errata.adoc
  clusters/release_notes/mce_known_issues.adoc
  edge_manager/edge_mgr_arch.adoc
  edge_manager/edge_mgr_auto_register.adoc
  edge_manager/edge_mgr_manage_devices_intro.adoc
  edge_manager/main.adoc
  gitops/deploy_gitops.adoc
  gitops/gitops_registering.adoc
  install/cleanup_reinstall.adoc
  mce_acm_integration/siteconfig/siteconfig_enable.adoc
  networking/submariner/deploy_subm_console.adoc
  networking/submariner/subm_disconnected.adoc
  networking/submariner/uninstall_subm.adoc
  observability/use_observability.adoc
  release_notes/acm_errata.adoc
  release_notes/known_issues_install.adoc
  secure_cluster/cert_manage.adoc
Labels: lgtm

#7746 https://issues.redhat.com/browse/ACM-19794 Fix typo
  mce_acm_integration/discover_hosted/acm_discover_hosted.adoc
Labels: lgtm

#7748 https://issues.redhat.com/browse/ACM-19664 Remove OCP link
  clusters/assisted_installer/ai_enable_cim.adoc
Labels: lgtm

#7726 https://issues.redhat.com/browse/ACM-19667
  secure_cluster/cert_intro.adoc
  secure_cluster/cert_manage.adoc
  secure_cluster/certificates.adoc
  secure_cluster/main.adoc
  secure_cluster/securing_cluster_intro.adoc
Labels: lgtm

#7752 Swope catch up clean up reinstall
  install/cleanup_reinstall.adoc
Labels: needs-rebase

#7755 2.13 Refresh
  clusters/assisted_installer/ai_enable_cim.adoc
  edge_manager/edge_mgr_build_images.adoc
  edge_manager/edge_mgr_build_images_platform_requirements.adoc
  edge_manager/edge_mgr_device_lifecycle_hooks.adoc
  edge_manager/edge_mgr_enable.adoc
  edge_manager/edge_mgr_enroll_devices.adoc
  edge_manager/edge_mgr_enrollment.adoc
  edge_manager/edge_mgr_field_selector.adoc
  edge_manager/edge_mgr_fleets.adoc
  edge_manager/edge_mgr_images.adoc
  edge_manager/edge_mgr_images_consider.adoc
  edge_manager/edge_mgr_label_devices.adoc
  edge_manager/edge_mgr_manage_apps_devices.adoc
  edge_manager/edge_mgr_manage_config_git_repo.adoc
  edge_manager/edge_mgr_manage_devices_intro.adoc
  edge_manager/edge_mgr_manage_os_config.adoc
  edge_manager/edge_mgr_monitor_device_resources.adoc
  edge_manager/edge_mgr_provision_intro.adoc
  edge_manager/edge_mgr_provision_physical.adoc
  edge_manager/edge_mgr_provision_virt.adoc
  edge_manager/edge_mgr_rbac.adoc
  edge_manager/edge_mgr_select_device_fleets.adoc
  edge_manager/edge_mgr_update_os_devices.adoc
  edge_manager/edge_mgr_using_labels_on_devices.adoc
  edge_manager/edge_mgr_view_devices.adoc
  mce_acm_integration/discover_hosted/acm_discover_hosted.adoc
  mce_acm_integration/main.adoc
  mce_acm_integration/siteconfig/siteconfig_about.adoc
  mce_acm_integration/siteconfig/siteconfig_intro.adoc
  observability/adv_config_obs.adoc
  observability/customize_observability.adoc
  observability/main.adoc
  observability/obs_config.adoc
  observability/obs_custom_alert.adoc
  observability/obs_custom_cert.adoc
  observability/obs_custom_rules.adoc
  observability/obs_metrics.adoc
  observability/obs_proxy.adoc
  observability/obs_pv_pvc.adoc
  observability/obs_rbac.adoc
  observability/obs_update_mco.adoc
  observability/observability_alerts.adoc
  observability/observability_arch.adoc
  observability/observability_enable.adoc
  observability/observe_environments_intro.adoc
  secure_cluster/cert_intro.adoc
  secure_cluster/cert_manage.adoc
  secure_cluster/certificates.adoc
  secure_cluster/main.adoc
  secure_cluster/rbac_implement_rhacm.adoc
  secure_cluster/securing_cluster_intro.adoc
Labels: lgtm

#7753 2.11 Refresh
  about/docinfo.xml
  access_control/docinfo.xml
  apis/docinfo.xml
  applications/docinfo.xml
  business_continuity/docinfo.xml
  clusters/docinfo.xml
  clusters/install_upgrade/config_infra_nodes_mce.adoc
  console/docinfo.xml
  gitops/docinfo.xml
  global_hub/docinfo.xml
  governance/cert_manage.adoc
  governance/docinfo.xml
  health_metrics/docinfo.xml
  install/config_infra_nodes_acm.adoc
  install/docinfo.xml
  klusterlet_add-ons/docinfo.xml
  networking/docinfo.xml
  observability/customize_observability.adoc
  observability/docinfo.xml
  observability/use_observability.adoc
  release_notes/docinfo.xml
  troubleshooting/docinfo.xml
Labels: lgtm

#7757 https://issues.redhat.com/browse/ACM-19804--creating virt and search
  about/.gitkeep
  applications/app_console.adoc
  console/console.adoc
  console/console_intro.adoc
  console/main.adoc
  console/manage_search.adoc
  gitops/gitops_console.adoc
  global_hub/global_search.adoc
  governance/.gitkeep
  modules/common-attributes.adoc
  release_notes/acm_whats_new.adoc
  search/create_search_collection.adoc
  search/custom_search_console.adoc
  search/docinfo.xml
  search/main.adoc
  search/master.adoc
  search/modules
  search/query_search_console.adoc
  search/search_console.adoc
  search/search_intro.adoc
  search/search_klusterlet_addon.adoc
  troubleshooting/trouble_shared_memory.adoc
  virtualization/docinfo.xml
  virtualization/enable_vm_actions.adoc
  virtualization/main.adoc
  virtualization/master.adoc
  virtualization/modules
  virtualization/view_vm_metrics_observability.adoc
  virtualization/virtualization_intro.adoc
Labels: lgtm

#7764 https://issues.redhat.com/browse/ACM-16769 adding SME fixes for clean…
  business_continuity/backup_restore/backup_restore.adoc
Labels: lgtm

#7745 https://issues.redhat.com/browse/ACM-19884 2.13 CIM feature
  clusters/cluster_lifecycle/create_cluster_on_prem.adoc
  clusters/release_notes/mce_whats_new.adoc
Labels: lgtm

#7765 https://issues.redhat.com/browse/ACM-17812--Document image mirroring with SiteConfig
  mce_acm_integration/main.adoc
  mce_acm_integration/siteconfig/siteconfig_intro.adoc
  mce_acm_integration/siteconfig/siteconfig_mirror_images_disconnected.adoc
Labels: lgtm

#7767 https://issues.redhat.com/browse/ACM-17815
  business_continuity/backup_restore/backup_arch.adoc
  business_continuity/backup_restore/backup_install.adoc
  business_continuity/backup_restore/backup_intro.adoc
  business_continuity/backup_restore/backup_restore.adoc
Labels: lgtm

#7769 https://issues.redhat.com/browse/ACM-20045
  business_continuity/backup_restore/backup_restore.adoc
Labels: lgtm
